#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 95
#define LARGE_STATE_COUNT 15
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  sym_identifier = 1,
  anon_sym_POUNDcheck = 2,
  anon_sym_POUNDeval = 3,
  anon_sym_POUNDreduce = 4,
  anon_sym_inductive = 5,
  anon_sym_where = 6,
  anon_sym_PIPE = 7,
  anon_sym_COLON = 8,
  anon_sym_namespace = 9,
  anon_sym_end = 10,
  anon_sym_section = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_ = 14,
  anon_sym_def = 15,
  anon_sym_COLON_EQ = 16,
  anon_sym_theorem = 17,
  anon_sym_example = 18,
  anon_sym_if = 19,
  anon_sym_then = 20,
  anon_sym_else = 21,
  anon_sym_fun = 22,
  anon_sym_EQ_GT = 23,
  anon_sym_STAR = 24,
  anon_sym_PLUS = 25,
  anon_sym_DASH = 26,
  anon_sym_EQ = 27,
  anon_sym_LT = 28,
  anon_sym_GT = 29,
  anon_sym_DQUOTE = 30,
  anon_sym_LBRACE = 31,
  anon_sym_RBRACE = 32,
  sym__string_content = 33,
  sym_comment = 34,
  sym_number = 35,
  sym_source_file = 36,
  sym__command = 37,
  sym_hash_command = 38,
  sym_inductive_type = 39,
  sym_constructor = 40,
  sym_namespace_definition = 41,
  sym_section_definition = 42,
  sym_parameter_list = 43,
  sym_annotated = 44,
  sym__type_annotation = 45,
  sym_function_annotation = 46,
  sym_function_definition = 47,
  sym_theorem_definition = 48,
  sym_example_definition = 49,
  sym__expression = 50,
  sym__parenthesized_expression = 51,
  sym_conditional = 52,
  sym_lambda = 53,
  sym_function_application = 54,
  sym_binary_expression = 55,
  sym_comparison = 56,
  sym_string = 57,
  sym_interpolation = 58,
  aux_sym_source_file_repeat1 = 59,
  aux_sym_inductive_type_repeat1 = 60,
  aux_sym_parameter_list_repeat1 = 61,
  aux_sym_function_application_repeat1 = 62,
  aux_sym_string_repeat1 = 63,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_POUNDcheck] = "#check",
  [anon_sym_POUNDeval] = "#eval",
  [anon_sym_POUNDreduce] = "#reduce",
  [anon_sym_inductive] = "inductive",
  [anon_sym_where] = "where",
  [anon_sym_PIPE] = "|",
  [anon_sym_COLON] = ":",
  [anon_sym_namespace] = "namespace",
  [anon_sym_end] = "end",
  [anon_sym_section] = "section",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_] = "→",
  [anon_sym_def] = "def",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_theorem] = "theorem",
  [anon_sym_example] = "example",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_fun] = "fun",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ] = "=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym__string_content] = "_string_content",
  [sym_comment] = "comment",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym__command] = "_command",
  [sym_hash_command] = "hash_command",
  [sym_inductive_type] = "inductive_type",
  [sym_constructor] = "constructor",
  [sym_namespace_definition] = "namespace_definition",
  [sym_section_definition] = "section_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_annotated] = "annotated",
  [sym__type_annotation] = "_type_annotation",
  [sym_function_annotation] = "function_annotation",
  [sym_function_definition] = "function_definition",
  [sym_theorem_definition] = "theorem_definition",
  [sym_example_definition] = "example_definition",
  [sym__expression] = "_expression",
  [sym__parenthesized_expression] = "_parenthesized_expression",
  [sym_conditional] = "conditional",
  [sym_lambda] = "lambda",
  [sym_function_application] = "function_application",
  [sym_binary_expression] = "binary_expression",
  [sym_comparison] = "comparison",
  [sym_string] = "string",
  [sym_interpolation] = "interpolation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_inductive_type_repeat1] = "inductive_type_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_function_application_repeat1] = "function_application_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_POUNDcheck] = anon_sym_POUNDcheck,
  [anon_sym_POUNDeval] = anon_sym_POUNDeval,
  [anon_sym_POUNDreduce] = anon_sym_POUNDreduce,
  [anon_sym_inductive] = anon_sym_inductive,
  [anon_sym_where] = anon_sym_where,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_section] = anon_sym_section,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_] = anon_sym_,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_theorem] = anon_sym_theorem,
  [anon_sym_example] = anon_sym_example,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_fun] = anon_sym_fun,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__string_content] = sym__string_content,
  [sym_comment] = sym_comment,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym__command] = sym__command,
  [sym_hash_command] = sym_hash_command,
  [sym_inductive_type] = sym_inductive_type,
  [sym_constructor] = sym_constructor,
  [sym_namespace_definition] = sym_namespace_definition,
  [sym_section_definition] = sym_section_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_annotated] = sym_annotated,
  [sym__type_annotation] = sym__type_annotation,
  [sym_function_annotation] = sym_function_annotation,
  [sym_function_definition] = sym_function_definition,
  [sym_theorem_definition] = sym_theorem_definition,
  [sym_example_definition] = sym_example_definition,
  [sym__expression] = sym__expression,
  [sym__parenthesized_expression] = sym__parenthesized_expression,
  [sym_conditional] = sym_conditional,
  [sym_lambda] = sym_lambda,
  [sym_function_application] = sym_function_application,
  [sym_binary_expression] = sym_binary_expression,
  [sym_comparison] = sym_comparison,
  [sym_string] = sym_string,
  [sym_interpolation] = sym_interpolation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_inductive_type_repeat1] = aux_sym_inductive_type_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_function_application_repeat1] = aux_sym_function_application_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDcheck] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDeval] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDreduce] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inductive] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_where] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_section] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_theorem] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_example] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fun] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__command] = {
    .visible = false,
    .named = true,
  },
  [sym_hash_command] = {
    .visible = true,
    .named = true,
  },
  [sym_inductive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_constructor] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_section_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_annotated] = {
    .visible = true,
    .named = true,
  },
  [sym__type_annotation] = {
    .visible = false,
    .named = true,
  },
  [sym_function_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_theorem_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_example_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__parenthesized_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_function_application] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_inductive_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_application_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_constructors = 2,
  field_name = 3,
  field_parameters = 4,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_constructors] = "constructors",
  [field_name] = "name",
  [field_parameters] = "parameters",
};

static const TSFieldMapSlice ts_field_map_slices[5] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arguments, 1},
    {field_name, 0},
  [2] =
    {field_constructors, 3},
    {field_name, 1},
  [4] =
    {field_name, 1},
  [5] =
    {field_name, 1},
    {field_parameters, 2},
};

static TSSymbol ts_alias_sequences[5][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '#') ADVANCE(8);
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '*') ADVANCE(33);
      if (lookahead == '+') ADVANCE(34);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == ':') ADVANCE(27);
      if (lookahead == '<') ADVANCE(38);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '{') ADVANCE(41);
      if (lookahead == '|') ADVANCE(25);
      if (lookahead == '}') ADVANCE(42);
      if (lookahead == 8594) ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '-') ADVANCE(44);
      if (lookahead == '{') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ':') ADVANCE(27);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ':') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(46);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(15);
      if (lookahead == 'e') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'k') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 19:
      if (lookahead == 'v') ADVANCE(7);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '#') ADVANCE(8);
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '*') ADVANCE(33);
      if (lookahead == '+') ADVANCE(34);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '<') ADVANCE(38);
      if (lookahead == '=') ADVANCE(36);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '}') ADVANCE(42);
      if (lookahead == 8594) ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(20)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUNDcheck);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_POUNDeval);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_POUNDreduce);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(46);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(32);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__string_content);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '-') ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '-') ADVANCE(44);
      if (lookahead == '{') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(43);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead == 'w') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(10);
      if (lookahead == 'n') ADVANCE(11);
      if (lookahead == 'x') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'h') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'h') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'm') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(31);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_fun);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(35);
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(38);
      END_STATE();
    case 32:
      if (lookahead == 'c') ADVANCE(39);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 40:
      if (lookahead == 'p') ADVANCE(46);
      END_STATE();
    case 41:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_where);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 46:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 48:
      if (lookahead == 'm') ADVANCE(53);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_example);
      END_STATE();
    case 50:
      if (lookahead == 'v') ADVANCE(54);
      END_STATE();
    case 51:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_section);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_theorem);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_inductive);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 20},
  [3] = {.lex_state = 20},
  [4] = {.lex_state = 20},
  [5] = {.lex_state = 20},
  [6] = {.lex_state = 20},
  [7] = {.lex_state = 20},
  [8] = {.lex_state = 20},
  [9] = {.lex_state = 20},
  [10] = {.lex_state = 20},
  [11] = {.lex_state = 20},
  [12] = {.lex_state = 20},
  [13] = {.lex_state = 20},
  [14] = {.lex_state = 20},
  [15] = {.lex_state = 20},
  [16] = {.lex_state = 20},
  [17] = {.lex_state = 20},
  [18] = {.lex_state = 20},
  [19] = {.lex_state = 20},
  [20] = {.lex_state = 20},
  [21] = {.lex_state = 20},
  [22] = {.lex_state = 20},
  [23] = {.lex_state = 20},
  [24] = {.lex_state = 20},
  [25] = {.lex_state = 20},
  [26] = {.lex_state = 20},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 20},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 20},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_POUNDcheck] = ACTIONS(1),
    [anon_sym_POUNDeval] = ACTIONS(1),
    [anon_sym_POUNDreduce] = ACTIONS(1),
    [anon_sym_inductive] = ACTIONS(1),
    [anon_sym_where] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_section] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_theorem] = ACTIONS(1),
    [anon_sym_example] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_fun] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(81),
    [sym__command] = STATE(30),
    [sym_hash_command] = STATE(30),
    [sym_inductive_type] = STATE(30),
    [sym_namespace_definition] = STATE(30),
    [sym_section_definition] = STATE(30),
    [sym_function_definition] = STATE(30),
    [sym_theorem_definition] = STATE(30),
    [sym_example_definition] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUNDcheck] = ACTIONS(7),
    [anon_sym_POUNDeval] = ACTIONS(7),
    [anon_sym_POUNDreduce] = ACTIONS(7),
    [anon_sym_inductive] = ACTIONS(9),
    [anon_sym_namespace] = ACTIONS(11),
    [anon_sym_section] = ACTIONS(13),
    [anon_sym_def] = ACTIONS(15),
    [anon_sym_theorem] = ACTIONS(17),
    [anon_sym_example] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_POUNDcheck] = ACTIONS(21),
    [anon_sym_POUNDeval] = ACTIONS(21),
    [anon_sym_POUNDreduce] = ACTIONS(21),
    [anon_sym_inductive] = ACTIONS(23),
    [anon_sym_namespace] = ACTIONS(23),
    [anon_sym_end] = ACTIONS(23),
    [anon_sym_section] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_] = ACTIONS(21),
    [anon_sym_def] = ACTIONS(23),
    [anon_sym_COLON_EQ] = ACTIONS(21),
    [anon_sym_theorem] = ACTIONS(23),
    [anon_sym_example] = ACTIONS(23),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_then] = ACTIONS(23),
    [anon_sym_else] = ACTIONS(23),
    [anon_sym_fun] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(21),
  },
  [3] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_identifier] = ACTIONS(33),
    [anon_sym_POUNDcheck] = ACTIONS(31),
    [anon_sym_POUNDeval] = ACTIONS(31),
    [anon_sym_POUNDreduce] = ACTIONS(31),
    [anon_sym_inductive] = ACTIONS(33),
    [anon_sym_namespace] = ACTIONS(33),
    [anon_sym_end] = ACTIONS(33),
    [anon_sym_section] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(31),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_] = ACTIONS(31),
    [anon_sym_def] = ACTIONS(33),
    [anon_sym_COLON_EQ] = ACTIONS(31),
    [anon_sym_theorem] = ACTIONS(33),
    [anon_sym_example] = ACTIONS(33),
    [anon_sym_if] = ACTIONS(33),
    [anon_sym_then] = ACTIONS(33),
    [anon_sym_else] = ACTIONS(33),
    [anon_sym_fun] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(31),
    [anon_sym_LT] = ACTIONS(31),
    [anon_sym_GT] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(31),
  },
  [4] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_identifier] = ACTIONS(37),
    [anon_sym_POUNDcheck] = ACTIONS(35),
    [anon_sym_POUNDeval] = ACTIONS(35),
    [anon_sym_POUNDreduce] = ACTIONS(35),
    [anon_sym_inductive] = ACTIONS(40),
    [anon_sym_namespace] = ACTIONS(40),
    [anon_sym_end] = ACTIONS(40),
    [anon_sym_section] = ACTIONS(40),
    [anon_sym_LPAREN] = ACTIONS(42),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_] = ACTIONS(35),
    [anon_sym_def] = ACTIONS(40),
    [anon_sym_COLON_EQ] = ACTIONS(35),
    [anon_sym_theorem] = ACTIONS(40),
    [anon_sym_example] = ACTIONS(40),
    [anon_sym_if] = ACTIONS(45),
    [anon_sym_then] = ACTIONS(40),
    [anon_sym_else] = ACTIONS(40),
    [anon_sym_fun] = ACTIONS(48),
    [anon_sym_STAR] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(40),
    [anon_sym_EQ] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(51),
    [anon_sym_RBRACE] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(54),
  },
  [5] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_identifier] = ACTIONS(59),
    [anon_sym_POUNDcheck] = ACTIONS(57),
    [anon_sym_POUNDeval] = ACTIONS(57),
    [anon_sym_POUNDreduce] = ACTIONS(57),
    [anon_sym_inductive] = ACTIONS(59),
    [anon_sym_namespace] = ACTIONS(59),
    [anon_sym_end] = ACTIONS(59),
    [anon_sym_section] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_] = ACTIONS(57),
    [anon_sym_def] = ACTIONS(59),
    [anon_sym_COLON_EQ] = ACTIONS(57),
    [anon_sym_theorem] = ACTIONS(59),
    [anon_sym_example] = ACTIONS(59),
    [anon_sym_if] = ACTIONS(59),
    [anon_sym_then] = ACTIONS(59),
    [anon_sym_else] = ACTIONS(59),
    [anon_sym_fun] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(57),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(57),
  },
  [6] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_identifier] = ACTIONS(63),
    [anon_sym_POUNDcheck] = ACTIONS(61),
    [anon_sym_POUNDeval] = ACTIONS(61),
    [anon_sym_POUNDreduce] = ACTIONS(61),
    [anon_sym_inductive] = ACTIONS(63),
    [anon_sym_namespace] = ACTIONS(63),
    [anon_sym_end] = ACTIONS(63),
    [anon_sym_section] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [anon_sym_] = ACTIONS(61),
    [anon_sym_def] = ACTIONS(63),
    [anon_sym_COLON_EQ] = ACTIONS(61),
    [anon_sym_theorem] = ACTIONS(63),
    [anon_sym_example] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(63),
    [anon_sym_then] = ACTIONS(63),
    [anon_sym_else] = ACTIONS(63),
    [anon_sym_fun] = ACTIONS(63),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(61),
  },
  [7] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_identifier] = ACTIONS(63),
    [anon_sym_POUNDcheck] = ACTIONS(61),
    [anon_sym_POUNDeval] = ACTIONS(61),
    [anon_sym_POUNDreduce] = ACTIONS(61),
    [anon_sym_inductive] = ACTIONS(63),
    [anon_sym_namespace] = ACTIONS(63),
    [anon_sym_end] = ACTIONS(63),
    [anon_sym_section] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [anon_sym_] = ACTIONS(61),
    [anon_sym_def] = ACTIONS(63),
    [anon_sym_COLON_EQ] = ACTIONS(61),
    [anon_sym_theorem] = ACTIONS(63),
    [anon_sym_example] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(63),
    [anon_sym_then] = ACTIONS(63),
    [anon_sym_else] = ACTIONS(63),
    [anon_sym_fun] = ACTIONS(63),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(63),
    [anon_sym_EQ] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(61),
  },
  [8] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_identifier] = ACTIONS(63),
    [anon_sym_POUNDcheck] = ACTIONS(61),
    [anon_sym_POUNDeval] = ACTIONS(61),
    [anon_sym_POUNDreduce] = ACTIONS(61),
    [anon_sym_inductive] = ACTIONS(63),
    [anon_sym_namespace] = ACTIONS(63),
    [anon_sym_end] = ACTIONS(63),
    [anon_sym_section] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [anon_sym_] = ACTIONS(61),
    [anon_sym_def] = ACTIONS(63),
    [anon_sym_COLON_EQ] = ACTIONS(61),
    [anon_sym_theorem] = ACTIONS(63),
    [anon_sym_example] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(63),
    [anon_sym_then] = ACTIONS(63),
    [anon_sym_else] = ACTIONS(63),
    [anon_sym_fun] = ACTIONS(63),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(63),
    [anon_sym_EQ] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(61),
  },
  [9] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym_identifier] = ACTIONS(67),
    [anon_sym_POUNDcheck] = ACTIONS(65),
    [anon_sym_POUNDeval] = ACTIONS(65),
    [anon_sym_POUNDreduce] = ACTIONS(65),
    [anon_sym_inductive] = ACTIONS(67),
    [anon_sym_namespace] = ACTIONS(67),
    [anon_sym_end] = ACTIONS(67),
    [anon_sym_section] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(65),
    [anon_sym_RPAREN] = ACTIONS(65),
    [anon_sym_] = ACTIONS(65),
    [anon_sym_def] = ACTIONS(67),
    [anon_sym_COLON_EQ] = ACTIONS(65),
    [anon_sym_theorem] = ACTIONS(67),
    [anon_sym_example] = ACTIONS(67),
    [anon_sym_if] = ACTIONS(67),
    [anon_sym_then] = ACTIONS(67),
    [anon_sym_else] = ACTIONS(67),
    [anon_sym_fun] = ACTIONS(67),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(65),
    [anon_sym_LT] = ACTIONS(65),
    [anon_sym_GT] = ACTIONS(65),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_RBRACE] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(65),
  },
  [10] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [anon_sym_POUNDcheck] = ACTIONS(69),
    [anon_sym_POUNDeval] = ACTIONS(69),
    [anon_sym_POUNDreduce] = ACTIONS(69),
    [anon_sym_inductive] = ACTIONS(73),
    [anon_sym_namespace] = ACTIONS(73),
    [anon_sym_end] = ACTIONS(73),
    [anon_sym_section] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(75),
    [anon_sym_RPAREN] = ACTIONS(69),
    [anon_sym_] = ACTIONS(69),
    [anon_sym_def] = ACTIONS(73),
    [anon_sym_COLON_EQ] = ACTIONS(69),
    [anon_sym_theorem] = ACTIONS(73),
    [anon_sym_example] = ACTIONS(73),
    [anon_sym_if] = ACTIONS(77),
    [anon_sym_then] = ACTIONS(73),
    [anon_sym_else] = ACTIONS(73),
    [anon_sym_fun] = ACTIONS(79),
    [anon_sym_STAR] = ACTIONS(69),
    [anon_sym_PLUS] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_EQ] = ACTIONS(69),
    [anon_sym_LT] = ACTIONS(69),
    [anon_sym_GT] = ACTIONS(69),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(69),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(83),
  },
  [11] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(85),
    [sym_identifier] = ACTIONS(71),
    [anon_sym_POUNDcheck] = ACTIONS(85),
    [anon_sym_POUNDeval] = ACTIONS(85),
    [anon_sym_POUNDreduce] = ACTIONS(85),
    [anon_sym_inductive] = ACTIONS(87),
    [anon_sym_namespace] = ACTIONS(87),
    [anon_sym_end] = ACTIONS(87),
    [anon_sym_section] = ACTIONS(87),
    [anon_sym_LPAREN] = ACTIONS(75),
    [anon_sym_def] = ACTIONS(87),
    [anon_sym_theorem] = ACTIONS(87),
    [anon_sym_example] = ACTIONS(87),
    [anon_sym_if] = ACTIONS(77),
    [anon_sym_fun] = ACTIONS(79),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(89),
    [anon_sym_LT] = ACTIONS(91),
    [anon_sym_GT] = ACTIONS(91),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(83),
  },
  [12] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(93),
    [sym_identifier] = ACTIONS(71),
    [anon_sym_POUNDcheck] = ACTIONS(93),
    [anon_sym_POUNDeval] = ACTIONS(93),
    [anon_sym_POUNDreduce] = ACTIONS(93),
    [anon_sym_inductive] = ACTIONS(95),
    [anon_sym_namespace] = ACTIONS(95),
    [anon_sym_end] = ACTIONS(95),
    [anon_sym_section] = ACTIONS(95),
    [anon_sym_LPAREN] = ACTIONS(75),
    [anon_sym_def] = ACTIONS(95),
    [anon_sym_theorem] = ACTIONS(95),
    [anon_sym_example] = ACTIONS(95),
    [anon_sym_if] = ACTIONS(77),
    [anon_sym_fun] = ACTIONS(79),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(89),
    [anon_sym_LT] = ACTIONS(91),
    [anon_sym_GT] = ACTIONS(91),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(83),
  },
  [13] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(97),
    [sym_identifier] = ACTIONS(71),
    [anon_sym_POUNDcheck] = ACTIONS(97),
    [anon_sym_POUNDeval] = ACTIONS(97),
    [anon_sym_POUNDreduce] = ACTIONS(97),
    [anon_sym_inductive] = ACTIONS(99),
    [anon_sym_namespace] = ACTIONS(99),
    [anon_sym_end] = ACTIONS(99),
    [anon_sym_section] = ACTIONS(99),
    [anon_sym_LPAREN] = ACTIONS(75),
    [anon_sym_def] = ACTIONS(99),
    [anon_sym_theorem] = ACTIONS(99),
    [anon_sym_example] = ACTIONS(99),
    [anon_sym_if] = ACTIONS(77),
    [anon_sym_fun] = ACTIONS(79),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(89),
    [anon_sym_LT] = ACTIONS(91),
    [anon_sym_GT] = ACTIONS(91),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(83),
  },
  [14] = {
    [sym__expression] = STATE(9),
    [sym__parenthesized_expression] = STATE(9),
    [sym_conditional] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_function_application] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_comparison] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_function_application_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(101),
    [sym_identifier] = ACTIONS(71),
    [anon_sym_POUNDcheck] = ACTIONS(101),
    [anon_sym_POUNDeval] = ACTIONS(101),
    [anon_sym_POUNDreduce] = ACTIONS(101),
    [anon_sym_inductive] = ACTIONS(103),
    [anon_sym_namespace] = ACTIONS(103),
    [anon_sym_end] = ACTIONS(103),
    [anon_sym_section] = ACTIONS(103),
    [anon_sym_LPAREN] = ACTIONS(75),
    [anon_sym_def] = ACTIONS(103),
    [anon_sym_theorem] = ACTIONS(103),
    [anon_sym_example] = ACTIONS(103),
    [anon_sym_if] = ACTIONS(77),
    [anon_sym_fun] = ACTIONS(79),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(89),
    [anon_sym_LT] = ACTIONS(91),
    [anon_sym_GT] = ACTIONS(91),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(83),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 13,
      anon_sym_inductive,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fun,
      anon_sym_DASH,
      sym_identifier,
    ACTIONS(105), 16,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_number,
  [37] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 13,
      anon_sym_inductive,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fun,
      anon_sym_DASH,
      sym_identifier,
    ACTIONS(109), 16,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_number,
  [74] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 13,
      anon_sym_inductive,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fun,
      anon_sym_DASH,
      sym_identifier,
    ACTIONS(113), 16,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_number,
  [111] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_STAR,
    ACTIONS(27), 1,
      anon_sym_PLUS,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(83), 1,
      sym_number,
    ACTIONS(89), 1,
      anon_sym_EQ,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    ACTIONS(119), 1,
      anon_sym_,
    STATE(10), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(9), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [168] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_STAR,
    ACTIONS(27), 1,
      anon_sym_PLUS,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(83), 1,
      sym_number,
    ACTIONS(89), 1,
      anon_sym_EQ,
    ACTIONS(121), 1,
      anon_sym_COLON_EQ,
    STATE(10), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(9), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [222] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_STAR,
    ACTIONS(27), 1,
      anon_sym_PLUS,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(83), 1,
      sym_number,
    ACTIONS(89), 1,
      anon_sym_EQ,
    ACTIONS(123), 1,
      anon_sym_else,
    STATE(10), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(9), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [276] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_STAR,
    ACTIONS(27), 1,
      anon_sym_PLUS,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(83), 1,
      sym_number,
    ACTIONS(89), 1,
      anon_sym_EQ,
    ACTIONS(125), 1,
      anon_sym_COLON_EQ,
    STATE(10), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(9), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [330] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_STAR,
    ACTIONS(27), 1,
      anon_sym_PLUS,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(83), 1,
      sym_number,
    ACTIONS(89), 1,
      anon_sym_EQ,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    STATE(10), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(9), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [384] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_STAR,
    ACTIONS(27), 1,
      anon_sym_PLUS,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(83), 1,
      sym_number,
    ACTIONS(89), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_then,
    STATE(10), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(9), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [438] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_STAR,
    ACTIONS(27), 1,
      anon_sym_PLUS,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(83), 1,
      sym_number,
    ACTIONS(89), 1,
      anon_sym_EQ,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
    STATE(10), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(9), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [492] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_STAR,
    ACTIONS(27), 1,
      anon_sym_PLUS,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(83), 1,
      sym_number,
    ACTIONS(89), 1,
      anon_sym_EQ,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(9), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [546] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_STAR,
    ACTIONS(27), 1,
      anon_sym_PLUS,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(83), 1,
      sym_number,
    ACTIONS(89), 1,
      anon_sym_EQ,
    ACTIONS(135), 1,
      anon_sym_COLON_EQ,
    STATE(10), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(9), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [600] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_inductive,
    ACTIONS(145), 1,
      anon_sym_namespace,
    ACTIONS(148), 1,
      anon_sym_section,
    ACTIONS(151), 1,
      anon_sym_def,
    ACTIONS(154), 1,
      anon_sym_theorem,
    ACTIONS(157), 1,
      anon_sym_example,
    ACTIONS(137), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    ACTIONS(139), 3,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
    STATE(27), 9,
      sym__command,
      sym_hash_command,
      sym_inductive_type,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [642] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_inductive,
    ACTIONS(11), 1,
      anon_sym_namespace,
    ACTIONS(13), 1,
      anon_sym_section,
    ACTIONS(15), 1,
      anon_sym_def,
    ACTIONS(17), 1,
      anon_sym_theorem,
    ACTIONS(19), 1,
      anon_sym_example,
    ACTIONS(160), 1,
      anon_sym_end,
    ACTIONS(7), 3,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
    STATE(32), 9,
      sym__command,
      sym_hash_command,
      sym_inductive_type,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [683] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_inductive,
    ACTIONS(11), 1,
      anon_sym_namespace,
    ACTIONS(13), 1,
      anon_sym_section,
    ACTIONS(15), 1,
      anon_sym_def,
    ACTIONS(17), 1,
      anon_sym_theorem,
    ACTIONS(19), 1,
      anon_sym_example,
    ACTIONS(162), 1,
      anon_sym_end,
    ACTIONS(7), 3,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
    STATE(31), 9,
      sym__command,
      sym_hash_command,
      sym_inductive_type,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [724] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_inductive,
    ACTIONS(11), 1,
      anon_sym_namespace,
    ACTIONS(13), 1,
      anon_sym_section,
    ACTIONS(15), 1,
      anon_sym_def,
    ACTIONS(17), 1,
      anon_sym_theorem,
    ACTIONS(19), 1,
      anon_sym_example,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 3,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
    STATE(27), 9,
      sym__command,
      sym_hash_command,
      sym_inductive_type,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [765] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_inductive,
    ACTIONS(11), 1,
      anon_sym_namespace,
    ACTIONS(13), 1,
      anon_sym_section,
    ACTIONS(15), 1,
      anon_sym_def,
    ACTIONS(17), 1,
      anon_sym_theorem,
    ACTIONS(19), 1,
      anon_sym_example,
    ACTIONS(166), 1,
      anon_sym_end,
    ACTIONS(7), 3,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
    STATE(27), 9,
      sym__command,
      sym_hash_command,
      sym_inductive_type,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [806] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_inductive,
    ACTIONS(11), 1,
      anon_sym_namespace,
    ACTIONS(13), 1,
      anon_sym_section,
    ACTIONS(15), 1,
      anon_sym_def,
    ACTIONS(17), 1,
      anon_sym_theorem,
    ACTIONS(19), 1,
      anon_sym_example,
    ACTIONS(168), 1,
      anon_sym_end,
    ACTIONS(7), 3,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
    STATE(27), 9,
      sym__command,
      sym_hash_command,
      sym_inductive_type,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [847] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(170), 1,
      sym_identifier,
    ACTIONS(172), 1,
      sym_number,
    STATE(83), 2,
      sym__type_annotation,
      sym_function_annotation,
    STATE(18), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [883] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(176), 1,
      sym_number,
    STATE(22), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [915] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      sym_number,
    STATE(2), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [947] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(182), 1,
      sym_identifier,
    ACTIONS(184), 1,
      sym_number,
    STATE(8), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [979] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(188), 1,
      sym_number,
    STATE(7), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1011] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(192), 1,
      sym_number,
    STATE(6), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1043] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(194), 1,
      sym_identifier,
    ACTIONS(196), 1,
      sym_number,
    STATE(5), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1075] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_PIPE,
    STATE(45), 2,
      sym_constructor,
      aux_sym_inductive_type_repeat1,
    ACTIONS(198), 11,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_inductive,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1099] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(202), 1,
      sym_identifier,
    ACTIONS(204), 1,
      sym_number,
    STATE(24), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1131] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(206), 1,
      sym_identifier,
    ACTIONS(208), 1,
      sym_number,
    STATE(13), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1163] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      sym_number,
    STATE(19), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1195] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(214), 1,
      sym_identifier,
    ACTIONS(216), 1,
      sym_number,
    STATE(21), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1227] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    STATE(45), 2,
      sym_constructor,
      aux_sym_inductive_type_repeat1,
    ACTIONS(218), 11,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_inductive,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1251] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(225), 1,
      sym_number,
    STATE(14), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1283] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(227), 1,
      sym_identifier,
    ACTIONS(229), 1,
      sym_number,
    STATE(23), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1315] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(231), 1,
      sym_identifier,
    ACTIONS(233), 1,
      sym_number,
    STATE(20), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1347] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(235), 1,
      sym_identifier,
    ACTIONS(237), 1,
      sym_number,
    STATE(11), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1379] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(239), 1,
      sym_identifier,
    ACTIONS(241), 1,
      sym_number,
    STATE(3), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1411] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(243), 1,
      sym_identifier,
    ACTIONS(245), 1,
      sym_number,
    STATE(26), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1443] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(247), 1,
      sym_identifier,
    ACTIONS(249), 1,
      sym_number,
    STATE(25), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1475] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_fun,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(253), 1,
      sym_number,
    STATE(12), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 12,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_inductive,
      anon_sym_PIPE,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1525] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 11,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_inductive,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 11,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_inductive,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1559] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 11,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_inductive,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1576] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 11,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_inductive,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1593] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 11,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_inductive,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1610] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 11,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_inductive,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1627] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_identifier,
    ACTIONS(272), 1,
      anon_sym_COLON,
    ACTIONS(274), 1,
      anon_sym_LPAREN,
    ACTIONS(277), 2,
      anon_sym_COLON_EQ,
      anon_sym_EQ_GT,
    STATE(61), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1648] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym_identifier,
    ACTIONS(281), 1,
      anon_sym_COLON,
    ACTIONS(283), 1,
      anon_sym_LPAREN,
    ACTIONS(285), 2,
      anon_sym_COLON_EQ,
      anon_sym_EQ_GT,
    STATE(61), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1669] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_LPAREN,
    ACTIONS(287), 1,
      sym_identifier,
    ACTIONS(289), 1,
      anon_sym_COLON_EQ,
    STATE(91), 1,
      sym_parameter_list,
    STATE(62), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1689] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_LPAREN,
    ACTIONS(287), 1,
      sym_identifier,
    ACTIONS(291), 1,
      anon_sym_COLON,
    STATE(90), 1,
      sym_parameter_list,
    STATE(62), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1709] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_COLON,
    ACTIONS(293), 4,
      anon_sym_LPAREN,
      anon_sym_COLON_EQ,
      anon_sym_EQ_GT,
      sym_identifier,
  [1722] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_LPAREN,
    ACTIONS(287), 1,
      sym_identifier,
    STATE(82), 1,
      sym_parameter_list,
    STATE(62), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1739] = 5,
    ACTIONS(297), 1,
      anon_sym_DQUOTE,
    ACTIONS(299), 1,
      anon_sym_LBRACE,
    ACTIONS(302), 1,
      sym__string_content,
    ACTIONS(305), 1,
      sym_comment,
    STATE(67), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1756] = 5,
    ACTIONS(305), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_DQUOTE,
    ACTIONS(309), 1,
      anon_sym_LBRACE,
    ACTIONS(311), 1,
      sym__string_content,
    STATE(69), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1773] = 5,
    ACTIONS(305), 1,
      sym_comment,
    ACTIONS(309), 1,
      anon_sym_LBRACE,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
    ACTIONS(315), 1,
      sym__string_content,
    STATE(67), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1790] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_PIPE,
    STATE(40), 2,
      sym_constructor,
      aux_sym_inductive_type_repeat1,
  [1801] = 2,
    ACTIONS(305), 1,
      sym_comment,
    ACTIONS(317), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym__string_content,
  [1810] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_COLON,
  [1817] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      sym_identifier,
  [1824] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_COLON,
  [1831] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_COLON,
  [1838] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      sym_identifier,
  [1845] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      sym_identifier,
  [1852] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      sym_identifier,
  [1859] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      sym_identifier,
  [1866] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      sym_identifier,
  [1873] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      ts_builtin_sym_end,
  [1880] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_EQ_GT,
  [1887] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_RPAREN,
  [1894] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      sym_identifier,
  [1901] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      sym_identifier,
  [1908] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      sym_identifier,
  [1915] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_where,
  [1922] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      sym_identifier,
  [1929] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      sym_identifier,
  [1936] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_COLON,
  [1943] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_COLON_EQ,
  [1950] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      sym_identifier,
  [1957] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      sym_identifier,
  [1964] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      sym_identifier,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(15)] = 0,
  [SMALL_STATE(16)] = 37,
  [SMALL_STATE(17)] = 74,
  [SMALL_STATE(18)] = 111,
  [SMALL_STATE(19)] = 168,
  [SMALL_STATE(20)] = 222,
  [SMALL_STATE(21)] = 276,
  [SMALL_STATE(22)] = 330,
  [SMALL_STATE(23)] = 384,
  [SMALL_STATE(24)] = 438,
  [SMALL_STATE(25)] = 492,
  [SMALL_STATE(26)] = 546,
  [SMALL_STATE(27)] = 600,
  [SMALL_STATE(28)] = 642,
  [SMALL_STATE(29)] = 683,
  [SMALL_STATE(30)] = 724,
  [SMALL_STATE(31)] = 765,
  [SMALL_STATE(32)] = 806,
  [SMALL_STATE(33)] = 847,
  [SMALL_STATE(34)] = 883,
  [SMALL_STATE(35)] = 915,
  [SMALL_STATE(36)] = 947,
  [SMALL_STATE(37)] = 979,
  [SMALL_STATE(38)] = 1011,
  [SMALL_STATE(39)] = 1043,
  [SMALL_STATE(40)] = 1075,
  [SMALL_STATE(41)] = 1099,
  [SMALL_STATE(42)] = 1131,
  [SMALL_STATE(43)] = 1163,
  [SMALL_STATE(44)] = 1195,
  [SMALL_STATE(45)] = 1227,
  [SMALL_STATE(46)] = 1251,
  [SMALL_STATE(47)] = 1283,
  [SMALL_STATE(48)] = 1315,
  [SMALL_STATE(49)] = 1347,
  [SMALL_STATE(50)] = 1379,
  [SMALL_STATE(51)] = 1411,
  [SMALL_STATE(52)] = 1443,
  [SMALL_STATE(53)] = 1475,
  [SMALL_STATE(54)] = 1507,
  [SMALL_STATE(55)] = 1525,
  [SMALL_STATE(56)] = 1542,
  [SMALL_STATE(57)] = 1559,
  [SMALL_STATE(58)] = 1576,
  [SMALL_STATE(59)] = 1593,
  [SMALL_STATE(60)] = 1610,
  [SMALL_STATE(61)] = 1627,
  [SMALL_STATE(62)] = 1648,
  [SMALL_STATE(63)] = 1669,
  [SMALL_STATE(64)] = 1689,
  [SMALL_STATE(65)] = 1709,
  [SMALL_STATE(66)] = 1722,
  [SMALL_STATE(67)] = 1739,
  [SMALL_STATE(68)] = 1756,
  [SMALL_STATE(69)] = 1773,
  [SMALL_STATE(70)] = 1790,
  [SMALL_STATE(71)] = 1801,
  [SMALL_STATE(72)] = 1810,
  [SMALL_STATE(73)] = 1817,
  [SMALL_STATE(74)] = 1824,
  [SMALL_STATE(75)] = 1831,
  [SMALL_STATE(76)] = 1838,
  [SMALL_STATE(77)] = 1845,
  [SMALL_STATE(78)] = 1852,
  [SMALL_STATE(79)] = 1859,
  [SMALL_STATE(80)] = 1866,
  [SMALL_STATE(81)] = 1873,
  [SMALL_STATE(82)] = 1880,
  [SMALL_STATE(83)] = 1887,
  [SMALL_STATE(84)] = 1894,
  [SMALL_STATE(85)] = 1901,
  [SMALL_STATE(86)] = 1908,
  [SMALL_STATE(87)] = 1915,
  [SMALL_STATE(88)] = 1922,
  [SMALL_STATE(89)] = 1929,
  [SMALL_STATE(90)] = 1936,
  [SMALL_STATE(91)] = 1943,
  [SMALL_STATE(92)] = 1950,
  [SMALL_STATE(93)] = 1957,
  [SMALL_STATE(94)] = 1964,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 6),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 6),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 4),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda, 4),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_application_repeat1, 2),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(9),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_application_repeat1, 2),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(34),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(47),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(66),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(68),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(9),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 3),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_application_repeat1, 1),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_application_repeat1, 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_application, 2, .production_id = 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_application, 2, .production_id = 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_example_definition, 5),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_example_definition, 5),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, .production_id = 4),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5, .production_id = 4),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, .production_id = 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, .production_id = 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash_command, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash_command, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesized_expression, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__parenthesized_expression, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_annotation, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_annotation, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(46),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(73),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(85),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(94),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(79),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(84),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(74),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inductive_type, 4, .production_id = 2),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inductive_type_repeat1, 2),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inductive_type_repeat1, 2), SHIFT_REPEAT(78),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor, 4),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theorem_definition, 7, .production_id = 4),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 4, .production_id = 3),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_definition, 4, .production_id = 3),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theorem_definition, 6, .production_id = 3),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 5, .production_id = 3),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_definition, 5, .production_id = 3),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(61),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(77),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 1),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotated, 5),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotated, 5),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [299] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(52),
  [302] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(67),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [309] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [313] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [315] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [317] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [337] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_lean(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
