#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 127
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  anon_sym_POUNDeval = 1,
  anon_sym_namespace = 2,
  anon_sym_end = 3,
  anon_sym_section = 4,
  anon_sym_LPAREN = 5,
  anon_sym_COLON = 6,
  anon_sym_RPAREN = 7,
  anon_sym_ = 8,
  anon_sym_def = 9,
  anon_sym_COLON_EQ = 10,
  anon_sym_theorem = 11,
  anon_sym_STAR = 12,
  anon_sym_PLUS = 13,
  anon_sym_DASH = 14,
  anon_sym_DQUOTE = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  sym__string_content = 18,
  sym_identifier = 19,
  sym_number = 20,
  sym_source_file = 21,
  sym__command = 22,
  sym__hash_command = 23,
  sym_eval_command = 24,
  sym_namespace_definition = 25,
  sym_section_definition = 26,
  sym_parameter_list = 27,
  sym_annotated = 28,
  sym__type_annotation = 29,
  sym_function_annotation = 30,
  sym_function_definition = 31,
  sym_theorem_definition = 32,
  sym__expression = 33,
  sym__parenthesized_expression = 34,
  sym_argument_list = 35,
  sym_function_application = 36,
  sym_binary_expression = 37,
  sym_string = 38,
  sym_interpolation = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_parameter_list_repeat1 = 41,
  aux_sym_argument_list_repeat1 = 42,
  aux_sym_string_repeat1 = 43,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUNDeval] = "#eval",
  [anon_sym_namespace] = "namespace",
  [anon_sym_end] = "end",
  [anon_sym_section] = "section",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COLON] = ":",
  [anon_sym_RPAREN] = ")",
  [anon_sym_] = "→",
  [anon_sym_def] = "def",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_theorem] = "theorem",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym__string_content] = "_string_content",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym__command] = "_command",
  [sym__hash_command] = "_hash_command",
  [sym_eval_command] = "eval_command",
  [sym_namespace_definition] = "namespace_definition",
  [sym_section_definition] = "section_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_annotated] = "annotated",
  [sym__type_annotation] = "_type_annotation",
  [sym_function_annotation] = "function_annotation",
  [sym_function_definition] = "function_definition",
  [sym_theorem_definition] = "theorem_definition",
  [sym__expression] = "_expression",
  [sym__parenthesized_expression] = "_parenthesized_expression",
  [sym_argument_list] = "argument_list",
  [sym_function_application] = "function_application",
  [sym_binary_expression] = "binary_expression",
  [sym_string] = "string",
  [sym_interpolation] = "interpolation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUNDeval] = anon_sym_POUNDeval,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_section] = anon_sym_section,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_] = anon_sym_,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_theorem] = anon_sym_theorem,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__string_content] = sym__string_content,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym__command] = sym__command,
  [sym__hash_command] = sym__hash_command,
  [sym_eval_command] = sym_eval_command,
  [sym_namespace_definition] = sym_namespace_definition,
  [sym_section_definition] = sym_section_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_annotated] = sym_annotated,
  [sym__type_annotation] = sym__type_annotation,
  [sym_function_annotation] = sym_function_annotation,
  [sym_function_definition] = sym_function_definition,
  [sym_theorem_definition] = sym_theorem_definition,
  [sym__expression] = sym__expression,
  [sym__parenthesized_expression] = sym__parenthesized_expression,
  [sym_argument_list] = sym_argument_list,
  [sym_function_application] = sym_function_application,
  [sym_binary_expression] = sym_binary_expression,
  [sym_string] = sym_string,
  [sym_interpolation] = sym_interpolation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUNDeval] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_section] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_theorem] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__command] = {
    .visible = false,
    .named = true,
  },
  [sym__hash_command] = {
    .visible = false,
    .named = true,
  },
  [sym_eval_command] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_section_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_annotated] = {
    .visible = true,
    .named = true,
  },
  [sym__type_annotation] = {
    .visible = false,
    .named = true,
  },
  [sym_function_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_theorem_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__parenthesized_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_application] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_name = 2,
  field_parameters = 3,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_name] = "name",
  [field_parameters] = "parameters",
};

static const TSFieldMapSlice ts_field_map_slices[4] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arguments, 1},
    {field_name, 0},
  [2] =
    {field_name, 1},
  [3] =
    {field_name, 1},
    {field_parameters, 2},
};

static TSSymbol ts_alias_sequences[4][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == '*') ADVANCE(52);
      if (lookahead == '+') ADVANCE(53);
      if (lookahead == '-') ADVANCE(54);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == 'd') ADVANCE(65);
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead == 'n') ADVANCE(60);
      if (lookahead == 's') ADVANCE(66);
      if (lookahead == 't') ADVANCE(72);
      if (lookahead == '{') ADVANCE(56);
      if (lookahead == '}') ADVANCE(57);
      if (lookahead == 8594) ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == '*') ADVANCE(52);
      if (lookahead == '+') ADVANCE(53);
      if (lookahead == '-') ADVANCE(54);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == '}') ADVANCE(57);
      if (lookahead == 8594) ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '{') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(49);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(47);
      END_STATE();
    case 18:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(50);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 31:
      if (lookahead == 'v') ADVANCE(4);
      END_STATE();
    case 32:
      if (eof) ADVANCE(34);
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == '*') ADVANCE(52);
      if (lookahead == '+') ADVANCE(53);
      if (lookahead == '-') ADVANCE(54);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == 'd') ADVANCE(65);
      if (lookahead == 'n') ADVANCE(60);
      if (lookahead == 's') ADVANCE(66);
      if (lookahead == 't') ADVANCE(72);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(32)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 33:
      if (eof) ADVANCE(34);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == '*') ADVANCE(52);
      if (lookahead == '+') ADVANCE(53);
      if (lookahead == '-') ADVANCE(54);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == 'd') ADVANCE(11);
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 'n') ADVANCE(5);
      if (lookahead == 's') ADVANCE(12);
      if (lookahead == 't') ADVANCE(18);
      if (lookahead == '}') ADVANCE(57);
      if (lookahead == 8594) ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(33)
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_POUNDeval);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_namespace);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_end);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_section);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_section);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(49);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_def);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_theorem);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_theorem);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__string_content);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '{') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(75);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(63);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(83);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(69);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(39);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(71);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(62);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(82);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(37);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(48);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(67);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(79);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(51);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(68);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(64);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(41);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(81);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(77);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(70);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(80);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(73);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 33},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 32},
  [4] = {.lex_state = 32},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 32},
  [8] = {.lex_state = 32},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 33},
  [15] = {.lex_state = 33},
  [16] = {.lex_state = 33},
  [17] = {.lex_state = 33},
  [18] = {.lex_state = 33},
  [19] = {.lex_state = 33},
  [20] = {.lex_state = 33},
  [21] = {.lex_state = 33},
  [22] = {.lex_state = 33},
  [23] = {.lex_state = 33},
  [24] = {.lex_state = 33},
  [25] = {.lex_state = 33},
  [26] = {.lex_state = 32},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 32},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 32},
  [35] = {.lex_state = 32},
  [36] = {.lex_state = 32},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 32},
  [39] = {.lex_state = 32},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 33},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 33},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 33},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 33},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 33},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 33},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 33},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 33},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 33},
  [82] = {.lex_state = 33},
  [83] = {.lex_state = 33},
  [84] = {.lex_state = 33},
  [85] = {.lex_state = 33},
  [86] = {.lex_state = 33},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 33},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 2},
  [109] = {.lex_state = 1},
  [110] = {.lex_state = 32},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 32},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 33},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 1},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 1},
  [123] = {.lex_state = 1},
  [124] = {.lex_state = 33},
  [125] = {.lex_state = 1},
  [126] = {.lex_state = 1},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUNDeval] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_section] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_theorem] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(121),
    [sym__command] = STATE(19),
    [sym__hash_command] = STATE(19),
    [sym_eval_command] = STATE(19),
    [sym_namespace_definition] = STATE(19),
    [sym_section_definition] = STATE(19),
    [sym_function_definition] = STATE(19),
    [sym_theorem_definition] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUNDeval] = ACTIONS(5),
    [anon_sym_namespace] = ACTIONS(7),
    [anon_sym_section] = ACTIONS(9),
    [anon_sym_def] = ACTIONS(11),
    [anon_sym_theorem] = ACTIONS(13),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_number,
    STATE(6), 1,
      aux_sym_argument_list_repeat1,
    STATE(24), 1,
      sym_argument_list,
    ACTIONS(15), 4,
      anon_sym_POUNDeval,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(17), 5,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
    STATE(33), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [39] = 9,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_number,
    STATE(4), 1,
      aux_sym_argument_list_repeat1,
    STATE(24), 1,
      sym_argument_list,
    ACTIONS(17), 4,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
    ACTIONS(15), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(38), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [78] = 8,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_number,
    STATE(7), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(37), 4,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
    ACTIONS(35), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(38), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [114] = 4,
    STATE(9), 1,
      aux_sym_argument_list_repeat1,
    STATE(33), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
    ACTIONS(37), 6,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(35), 7,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [142] = 8,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_number,
    STATE(9), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(35), 4,
      anon_sym_POUNDeval,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 5,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
    STATE(33), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [178] = 8,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(52), 1,
      sym_number,
    STATE(7), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(41), 4,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
    ACTIONS(39), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(38), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [214] = 4,
    STATE(7), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(37), 5,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    STATE(38), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
    ACTIONS(35), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [242] = 8,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(64), 1,
      sym_number,
    STATE(9), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(39), 4,
      anon_sym_POUNDeval,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(41), 5,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
    STATE(33), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [278] = 7,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    STATE(11), 1,
      aux_sym_argument_list_repeat1,
    STATE(24), 1,
      sym_argument_list,
    ACTIONS(71), 2,
      sym_identifier,
      sym_number,
    STATE(45), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
    ACTIONS(15), 7,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACE,
  [311] = 6,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(71), 2,
      sym_identifier,
      sym_number,
    STATE(45), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
    ACTIONS(35), 7,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACE,
  [341] = 6,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(79), 2,
      sym_identifier,
      sym_number,
    STATE(45), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
    ACTIONS(39), 7,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACE,
  [371] = 3,
    STATE(12), 1,
      aux_sym_argument_list_repeat1,
    STATE(45), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
    ACTIONS(35), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
  [395] = 1,
    ACTIONS(82), 14,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_def,
      anon_sym_COLON_EQ,
      anon_sym_theorem,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACE,
  [412] = 7,
    ACTIONS(7), 1,
      anon_sym_namespace,
    ACTIONS(9), 1,
      anon_sym_section,
    ACTIONS(13), 1,
      anon_sym_theorem,
    ACTIONS(84), 1,
      anon_sym_POUNDeval,
    ACTIONS(86), 1,
      anon_sym_end,
    ACTIONS(88), 1,
      anon_sym_def,
    STATE(25), 8,
      sym__command,
      sym__hash_command,
      sym_eval_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      aux_sym_source_file_repeat1,
  [441] = 7,
    ACTIONS(7), 1,
      anon_sym_namespace,
    ACTIONS(9), 1,
      anon_sym_section,
    ACTIONS(13), 1,
      anon_sym_theorem,
    ACTIONS(84), 1,
      anon_sym_POUNDeval,
    ACTIONS(88), 1,
      anon_sym_def,
    ACTIONS(90), 1,
      anon_sym_end,
    STATE(23), 8,
      sym__command,
      sym__hash_command,
      sym_eval_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      aux_sym_source_file_repeat1,
  [470] = 1,
    ACTIONS(92), 14,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_def,
      anon_sym_COLON_EQ,
      anon_sym_theorem,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACE,
  [487] = 7,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 1,
      anon_sym_POUNDeval,
    ACTIONS(99), 1,
      anon_sym_namespace,
    ACTIONS(102), 1,
      anon_sym_section,
    ACTIONS(105), 1,
      anon_sym_def,
    ACTIONS(108), 1,
      anon_sym_theorem,
    STATE(18), 8,
      sym__command,
      sym__hash_command,
      sym_eval_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      aux_sym_source_file_repeat1,
  [516] = 7,
    ACTIONS(5), 1,
      anon_sym_POUNDeval,
    ACTIONS(7), 1,
      anon_sym_namespace,
    ACTIONS(9), 1,
      anon_sym_section,
    ACTIONS(11), 1,
      anon_sym_def,
    ACTIONS(13), 1,
      anon_sym_theorem,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    STATE(18), 8,
      sym__command,
      sym__hash_command,
      sym_eval_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      aux_sym_source_file_repeat1,
  [545] = 1,
    ACTIONS(113), 14,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_def,
      anon_sym_COLON_EQ,
      anon_sym_theorem,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACE,
  [562] = 7,
    ACTIONS(7), 1,
      anon_sym_namespace,
    ACTIONS(9), 1,
      anon_sym_section,
    ACTIONS(13), 1,
      anon_sym_theorem,
    ACTIONS(84), 1,
      anon_sym_POUNDeval,
    ACTIONS(88), 1,
      anon_sym_def,
    ACTIONS(115), 1,
      anon_sym_end,
    STATE(15), 8,
      sym__command,
      sym__hash_command,
      sym_eval_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      aux_sym_source_file_repeat1,
  [591] = 1,
    ACTIONS(117), 14,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_def,
      anon_sym_COLON_EQ,
      anon_sym_theorem,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACE,
  [608] = 7,
    ACTIONS(7), 1,
      anon_sym_namespace,
    ACTIONS(9), 1,
      anon_sym_section,
    ACTIONS(13), 1,
      anon_sym_theorem,
    ACTIONS(84), 1,
      anon_sym_POUNDeval,
    ACTIONS(88), 1,
      anon_sym_def,
    ACTIONS(119), 1,
      anon_sym_end,
    STATE(25), 8,
      sym__command,
      sym__hash_command,
      sym_eval_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      aux_sym_source_file_repeat1,
  [637] = 1,
    ACTIONS(121), 14,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_def,
      anon_sym_COLON_EQ,
      anon_sym_theorem,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACE,
  [654] = 7,
    ACTIONS(94), 1,
      anon_sym_end,
    ACTIONS(99), 1,
      anon_sym_namespace,
    ACTIONS(102), 1,
      anon_sym_section,
    ACTIONS(108), 1,
      anon_sym_theorem,
    ACTIONS(123), 1,
      anon_sym_POUNDeval,
    ACTIONS(126), 1,
      anon_sym_def,
    STATE(25), 8,
      sym__command,
      sym__hash_command,
      sym_eval_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      aux_sym_source_file_repeat1,
  [683] = 2,
    ACTIONS(129), 5,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(117), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [701] = 2,
    ACTIONS(131), 6,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(92), 7,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [719] = 3,
    ACTIONS(133), 1,
      anon_sym_STAR,
    ACTIONS(92), 6,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(131), 6,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
  [739] = 2,
    ACTIONS(135), 6,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(82), 7,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [757] = 2,
    ACTIONS(137), 6,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(121), 7,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [775] = 2,
    ACTIONS(139), 5,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(113), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [793] = 2,
    ACTIONS(129), 6,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(117), 7,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [811] = 4,
    ACTIONS(133), 1,
      anon_sym_STAR,
    ACTIONS(145), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(141), 4,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(143), 6,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
  [833] = 2,
    ACTIONS(137), 5,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(121), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [851] = 2,
    ACTIONS(131), 5,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(92), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [869] = 2,
    ACTIONS(135), 5,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(82), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [887] = 2,
    ACTIONS(139), 6,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(113), 7,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [905] = 4,
    ACTIONS(147), 1,
      anon_sym_STAR,
    ACTIONS(149), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(143), 5,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
  [927] = 3,
    ACTIONS(147), 1,
      anon_sym_STAR,
    ACTIONS(131), 5,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      sym_identifier,
    ACTIONS(92), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      sym_number,
  [947] = 1,
    ACTIONS(92), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
  [961] = 1,
    ACTIONS(117), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
  [975] = 6,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(157), 1,
      sym_number,
    STATE(118), 2,
      sym__type_annotation,
      sym_function_annotation,
    STATE(99), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [999] = 2,
    ACTIONS(159), 1,
      anon_sym_STAR,
    ACTIONS(92), 10,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
  [1015] = 1,
    ACTIONS(113), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
  [1029] = 3,
    ACTIONS(159), 1,
      anon_sym_STAR,
    ACTIONS(161), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(141), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
  [1047] = 1,
    ACTIONS(121), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
  [1061] = 1,
    ACTIONS(82), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
  [1075] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 1,
      sym_number,
    STATE(67), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1095] = 4,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(167), 2,
      sym_identifier,
      sym_number,
    STATE(35), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1113] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(169), 1,
      sym_number,
    STATE(56), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1133] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(171), 1,
      sym_number,
    STATE(103), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1153] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(173), 1,
      sym_number,
    STATE(105), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1173] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(175), 1,
      sym_number,
    STATE(107), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1193] = 3,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(177), 6,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
  [1209] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(185), 1,
      sym_number,
    STATE(54), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1229] = 3,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(187), 6,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
  [1245] = 4,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(193), 2,
      sym_identifier,
      sym_number,
    STATE(28), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1263] = 4,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(195), 2,
      sym_identifier,
      sym_number,
    STATE(27), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1281] = 2,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(92), 8,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1295] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym_number,
    STATE(59), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1315] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(199), 1,
      sym_number,
    STATE(17), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1335] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(201), 1,
      sym_number,
    STATE(104), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1355] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(203), 1,
      sym_number,
    STATE(101), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1375] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(205), 1,
      sym_number,
    STATE(65), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1395] = 3,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(177), 6,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
  [1411] = 4,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    ACTIONS(207), 2,
      sym_identifier,
      sym_number,
    STATE(43), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1429] = 3,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(209), 6,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
  [1445] = 4,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    ACTIONS(211), 2,
      sym_identifier,
      sym_number,
    STATE(40), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1463] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(199), 1,
      sym_number,
    STATE(17), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1483] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(213), 1,
      sym_number,
    STATE(82), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1503] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(215), 1,
      sym_number,
    STATE(77), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1523] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(217), 1,
      sym_number,
    STATE(106), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1543] = 2,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(92), 8,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1557] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(199), 1,
      sym_number,
    STATE(17), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1577] = 4,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(219), 2,
      sym_identifier,
      sym_number,
    STATE(39), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1595] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(221), 1,
      sym_number,
    STATE(73), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1615] = 3,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(209), 6,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
  [1631] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(223), 1,
      sym_number,
    STATE(79), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1651] = 3,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(187), 6,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
  [1667] = 5,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(225), 1,
      sym_number,
    STATE(102), 5,
      sym__expression,
      sym__parenthesized_expression,
      sym_function_application,
      sym_binary_expression,
      sym_string,
  [1687] = 1,
    ACTIONS(227), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
  [1697] = 2,
    ACTIONS(229), 1,
      anon_sym_STAR,
    ACTIONS(92), 6,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACE,
  [1709] = 1,
    ACTIONS(231), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
  [1719] = 1,
    ACTIONS(233), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
  [1729] = 1,
    ACTIONS(235), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
  [1739] = 1,
    ACTIONS(237), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDeval,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
  [1749] = 5,
    ACTIONS(239), 1,
      anon_sym_LPAREN,
    ACTIONS(241), 1,
      anon_sym_COLON_EQ,
    ACTIONS(243), 1,
      sym_identifier,
    STATE(124), 1,
      sym_parameter_list,
    STATE(98), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1766] = 5,
    ACTIONS(239), 1,
      anon_sym_LPAREN,
    ACTIONS(243), 1,
      sym_identifier,
    ACTIONS(245), 1,
      anon_sym_COLON_EQ,
    STATE(116), 1,
      sym_parameter_list,
    STATE(98), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1783] = 4,
    ACTIONS(247), 1,
      anon_sym_DQUOTE,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(251), 1,
      sym__string_content,
    STATE(93), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1797] = 4,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(253), 1,
      anon_sym_DQUOTE,
    ACTIONS(255), 1,
      sym__string_content,
    STATE(89), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1811] = 4,
    ACTIONS(257), 1,
      anon_sym_LPAREN,
    ACTIONS(260), 1,
      anon_sym_COLON_EQ,
    ACTIONS(262), 1,
      sym_identifier,
    STATE(91), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1825] = 4,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(251), 1,
      sym__string_content,
    ACTIONS(265), 1,
      anon_sym_DQUOTE,
    STATE(93), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1839] = 4,
    ACTIONS(267), 1,
      anon_sym_DQUOTE,
    ACTIONS(269), 1,
      anon_sym_LBRACE,
    ACTIONS(272), 1,
      sym__string_content,
    STATE(93), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1853] = 4,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(251), 1,
      sym__string_content,
    ACTIONS(275), 1,
      anon_sym_DQUOTE,
    STATE(93), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1867] = 4,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(277), 1,
      anon_sym_DQUOTE,
    ACTIONS(279), 1,
      sym__string_content,
    STATE(92), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1881] = 4,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(281), 1,
      anon_sym_DQUOTE,
    ACTIONS(283), 1,
      sym__string_content,
    STATE(94), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1895] = 4,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(251), 1,
      sym__string_content,
    ACTIONS(285), 1,
      anon_sym_DQUOTE,
    STATE(93), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1909] = 4,
    ACTIONS(239), 1,
      anon_sym_LPAREN,
    ACTIONS(287), 1,
      anon_sym_COLON_EQ,
    ACTIONS(289), 1,
      sym_identifier,
    STATE(91), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1923] = 4,
    ACTIONS(229), 1,
      anon_sym_STAR,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
    ACTIONS(293), 1,
      anon_sym_,
    ACTIONS(295), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1937] = 4,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(297), 1,
      anon_sym_DQUOTE,
    ACTIONS(299), 1,
      sym__string_content,
    STATE(97), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1951] = 3,
    ACTIONS(229), 1,
      anon_sym_STAR,
    ACTIONS(301), 1,
      anon_sym_RPAREN,
    ACTIONS(295), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1962] = 3,
    ACTIONS(229), 1,
      anon_sym_STAR,
    ACTIONS(303), 1,
      anon_sym_COLON_EQ,
    ACTIONS(295), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1973] = 3,
    ACTIONS(229), 1,
      anon_sym_STAR,
    ACTIONS(305), 1,
      anon_sym_RPAREN,
    ACTIONS(295), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1984] = 3,
    ACTIONS(229), 1,
      anon_sym_STAR,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    ACTIONS(295), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1995] = 3,
    ACTIONS(229), 1,
      anon_sym_STAR,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
    ACTIONS(295), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [2006] = 3,
    ACTIONS(229), 1,
      anon_sym_STAR,
    ACTIONS(311), 1,
      anon_sym_RBRACE,
    ACTIONS(295), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [2017] = 3,
    ACTIONS(229), 1,
      anon_sym_STAR,
    ACTIONS(313), 1,
      anon_sym_RPAREN,
    ACTIONS(295), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [2028] = 1,
    ACTIONS(315), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym__string_content,
  [2034] = 1,
    ACTIONS(317), 3,
      anon_sym_LPAREN,
      anon_sym_COLON_EQ,
      sym_identifier,
  [2040] = 1,
    ACTIONS(319), 1,
      anon_sym_COLON,
  [2044] = 1,
    ACTIONS(321), 1,
      sym_identifier,
  [2048] = 1,
    ACTIONS(323), 1,
      sym_identifier,
  [2052] = 1,
    ACTIONS(325), 1,
      sym_identifier,
  [2056] = 1,
    ACTIONS(327), 1,
      anon_sym_COLON,
  [2060] = 1,
    ACTIONS(329), 1,
      sym_identifier,
  [2064] = 1,
    ACTIONS(331), 1,
      anon_sym_COLON_EQ,
  [2068] = 1,
    ACTIONS(333), 1,
      sym_identifier,
  [2072] = 1,
    ACTIONS(335), 1,
      anon_sym_RPAREN,
  [2076] = 1,
    ACTIONS(337), 1,
      sym_identifier,
  [2080] = 1,
    ACTIONS(339), 1,
      sym_identifier,
  [2084] = 1,
    ACTIONS(341), 1,
      ts_builtin_sym_end,
  [2088] = 1,
    ACTIONS(343), 1,
      sym_identifier,
  [2092] = 1,
    ACTIONS(345), 1,
      sym_identifier,
  [2096] = 1,
    ACTIONS(347), 1,
      anon_sym_COLON_EQ,
  [2100] = 1,
    ACTIONS(349), 1,
      sym_identifier,
  [2104] = 1,
    ACTIONS(351), 1,
      sym_identifier,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 114,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 178,
  [SMALL_STATE(8)] = 214,
  [SMALL_STATE(9)] = 242,
  [SMALL_STATE(10)] = 278,
  [SMALL_STATE(11)] = 311,
  [SMALL_STATE(12)] = 341,
  [SMALL_STATE(13)] = 371,
  [SMALL_STATE(14)] = 395,
  [SMALL_STATE(15)] = 412,
  [SMALL_STATE(16)] = 441,
  [SMALL_STATE(17)] = 470,
  [SMALL_STATE(18)] = 487,
  [SMALL_STATE(19)] = 516,
  [SMALL_STATE(20)] = 545,
  [SMALL_STATE(21)] = 562,
  [SMALL_STATE(22)] = 591,
  [SMALL_STATE(23)] = 608,
  [SMALL_STATE(24)] = 637,
  [SMALL_STATE(25)] = 654,
  [SMALL_STATE(26)] = 683,
  [SMALL_STATE(27)] = 701,
  [SMALL_STATE(28)] = 719,
  [SMALL_STATE(29)] = 739,
  [SMALL_STATE(30)] = 757,
  [SMALL_STATE(31)] = 775,
  [SMALL_STATE(32)] = 793,
  [SMALL_STATE(33)] = 811,
  [SMALL_STATE(34)] = 833,
  [SMALL_STATE(35)] = 851,
  [SMALL_STATE(36)] = 869,
  [SMALL_STATE(37)] = 887,
  [SMALL_STATE(38)] = 905,
  [SMALL_STATE(39)] = 927,
  [SMALL_STATE(40)] = 947,
  [SMALL_STATE(41)] = 961,
  [SMALL_STATE(42)] = 975,
  [SMALL_STATE(43)] = 999,
  [SMALL_STATE(44)] = 1015,
  [SMALL_STATE(45)] = 1029,
  [SMALL_STATE(46)] = 1047,
  [SMALL_STATE(47)] = 1061,
  [SMALL_STATE(48)] = 1075,
  [SMALL_STATE(49)] = 1095,
  [SMALL_STATE(50)] = 1113,
  [SMALL_STATE(51)] = 1133,
  [SMALL_STATE(52)] = 1153,
  [SMALL_STATE(53)] = 1173,
  [SMALL_STATE(54)] = 1193,
  [SMALL_STATE(55)] = 1209,
  [SMALL_STATE(56)] = 1229,
  [SMALL_STATE(57)] = 1245,
  [SMALL_STATE(58)] = 1263,
  [SMALL_STATE(59)] = 1281,
  [SMALL_STATE(60)] = 1295,
  [SMALL_STATE(61)] = 1315,
  [SMALL_STATE(62)] = 1335,
  [SMALL_STATE(63)] = 1355,
  [SMALL_STATE(64)] = 1375,
  [SMALL_STATE(65)] = 1395,
  [SMALL_STATE(66)] = 1411,
  [SMALL_STATE(67)] = 1429,
  [SMALL_STATE(68)] = 1445,
  [SMALL_STATE(69)] = 1463,
  [SMALL_STATE(70)] = 1483,
  [SMALL_STATE(71)] = 1503,
  [SMALL_STATE(72)] = 1523,
  [SMALL_STATE(73)] = 1543,
  [SMALL_STATE(74)] = 1557,
  [SMALL_STATE(75)] = 1577,
  [SMALL_STATE(76)] = 1595,
  [SMALL_STATE(77)] = 1615,
  [SMALL_STATE(78)] = 1631,
  [SMALL_STATE(79)] = 1651,
  [SMALL_STATE(80)] = 1667,
  [SMALL_STATE(81)] = 1687,
  [SMALL_STATE(82)] = 1697,
  [SMALL_STATE(83)] = 1709,
  [SMALL_STATE(84)] = 1719,
  [SMALL_STATE(85)] = 1729,
  [SMALL_STATE(86)] = 1739,
  [SMALL_STATE(87)] = 1749,
  [SMALL_STATE(88)] = 1766,
  [SMALL_STATE(89)] = 1783,
  [SMALL_STATE(90)] = 1797,
  [SMALL_STATE(91)] = 1811,
  [SMALL_STATE(92)] = 1825,
  [SMALL_STATE(93)] = 1839,
  [SMALL_STATE(94)] = 1853,
  [SMALL_STATE(95)] = 1867,
  [SMALL_STATE(96)] = 1881,
  [SMALL_STATE(97)] = 1895,
  [SMALL_STATE(98)] = 1909,
  [SMALL_STATE(99)] = 1923,
  [SMALL_STATE(100)] = 1937,
  [SMALL_STATE(101)] = 1951,
  [SMALL_STATE(102)] = 1962,
  [SMALL_STATE(103)] = 1973,
  [SMALL_STATE(104)] = 1984,
  [SMALL_STATE(105)] = 1995,
  [SMALL_STATE(106)] = 2006,
  [SMALL_STATE(107)] = 2017,
  [SMALL_STATE(108)] = 2028,
  [SMALL_STATE(109)] = 2034,
  [SMALL_STATE(110)] = 2040,
  [SMALL_STATE(111)] = 2044,
  [SMALL_STATE(112)] = 2048,
  [SMALL_STATE(113)] = 2052,
  [SMALL_STATE(114)] = 2056,
  [SMALL_STATE(115)] = 2060,
  [SMALL_STATE(116)] = 2064,
  [SMALL_STATE(117)] = 2068,
  [SMALL_STATE(118)] = 2072,
  [SMALL_STATE(119)] = 2076,
  [SMALL_STATE(120)] = 2080,
  [SMALL_STATE(121)] = 2084,
  [SMALL_STATE(122)] = 2088,
  [SMALL_STATE(123)] = 2092,
  [SMALL_STATE(124)] = 2096,
  [SMALL_STATE(125)] = 2100,
  [SMALL_STATE(126)] = 2104,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(53),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(90),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(38),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(38),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(51),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(96),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(33),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(33),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(52),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(100),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(45),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesized_expression, 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(64),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(113),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(117),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(119),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(120),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_application, 2, .production_id = 1),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(55),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(123),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__parenthesized_expression, 3),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_application, 2, .production_id = 1),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eval_command, 2),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, .production_id = 3),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, .production_id = 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 4),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_definition, 5),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 5),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theorem_definition, 6),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_definition, 4),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(112),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(91),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [269] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(72),
  [272] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(93),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [281] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_annotation, 1),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_annotation, 3),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [315] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotated, 5),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [341] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_lean(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
