#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 90
#define LARGE_STATE_COUNT 17
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  sym_identifier = 1,
  anon_sym_POUNDcheck = 2,
  anon_sym_POUNDeval = 3,
  anon_sym_POUNDreduce = 4,
  anon_sym_namespace = 5,
  anon_sym_end = 6,
  anon_sym_section = 7,
  anon_sym_LPAREN = 8,
  anon_sym_COLON = 9,
  anon_sym_RPAREN = 10,
  anon_sym_ = 11,
  anon_sym_def = 12,
  anon_sym_COLON_EQ = 13,
  anon_sym_theorem = 14,
  anon_sym_example = 15,
  anon_sym_if = 16,
  anon_sym_then = 17,
  anon_sym_else = 18,
  anon_sym_fun = 19,
  anon_sym_EQ_GT = 20,
  anon_sym_STAR = 21,
  anon_sym_PLUS = 22,
  anon_sym_DASH = 23,
  anon_sym_EQ = 24,
  anon_sym_LT = 25,
  anon_sym_GT = 26,
  anon_sym_DQUOTE = 27,
  anon_sym_LBRACE = 28,
  anon_sym_RBRACE = 29,
  sym__string_content = 30,
  sym_comment = 31,
  sym_number = 32,
  sym_source_file = 33,
  sym__command = 34,
  sym__hash_command = 35,
  sym_check_command = 36,
  sym_eval_command = 37,
  sym_reduce_command = 38,
  sym_namespace_definition = 39,
  sym_section_definition = 40,
  sym_parameter_list = 41,
  sym_annotated = 42,
  sym__type_annotation = 43,
  sym_function_annotation = 44,
  sym_function_definition = 45,
  sym_theorem_definition = 46,
  sym_example_definition = 47,
  sym__expression = 48,
  sym__parenthesized_expression = 49,
  sym_conditional = 50,
  sym_lambda = 51,
  sym_function_application = 52,
  sym_binary_expression = 53,
  sym_comparison = 54,
  sym_string = 55,
  sym_interpolation = 56,
  aux_sym_source_file_repeat1 = 57,
  aux_sym_parameter_list_repeat1 = 58,
  aux_sym_function_application_repeat1 = 59,
  aux_sym_string_repeat1 = 60,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_POUNDcheck] = "#check",
  [anon_sym_POUNDeval] = "#eval",
  [anon_sym_POUNDreduce] = "#reduce",
  [anon_sym_namespace] = "namespace",
  [anon_sym_end] = "end",
  [anon_sym_section] = "section",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COLON] = ":",
  [anon_sym_RPAREN] = ")",
  [anon_sym_] = "→",
  [anon_sym_def] = "def",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_theorem] = "theorem",
  [anon_sym_example] = "example",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_fun] = "fun",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ] = "=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym__string_content] = "_string_content",
  [sym_comment] = "comment",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym__command] = "_command",
  [sym__hash_command] = "_hash_command",
  [sym_check_command] = "check_command",
  [sym_eval_command] = "eval_command",
  [sym_reduce_command] = "reduce_command",
  [sym_namespace_definition] = "namespace_definition",
  [sym_section_definition] = "section_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_annotated] = "annotated",
  [sym__type_annotation] = "_type_annotation",
  [sym_function_annotation] = "function_annotation",
  [sym_function_definition] = "function_definition",
  [sym_theorem_definition] = "theorem_definition",
  [sym_example_definition] = "example_definition",
  [sym__expression] = "_expression",
  [sym__parenthesized_expression] = "_parenthesized_expression",
  [sym_conditional] = "conditional",
  [sym_lambda] = "lambda",
  [sym_function_application] = "function_application",
  [sym_binary_expression] = "binary_expression",
  [sym_comparison] = "comparison",
  [sym_string] = "string",
  [sym_interpolation] = "interpolation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_function_application_repeat1] = "function_application_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_POUNDcheck] = anon_sym_POUNDcheck,
  [anon_sym_POUNDeval] = anon_sym_POUNDeval,
  [anon_sym_POUNDreduce] = anon_sym_POUNDreduce,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_section] = anon_sym_section,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_] = anon_sym_,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_theorem] = anon_sym_theorem,
  [anon_sym_example] = anon_sym_example,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_fun] = anon_sym_fun,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__string_content] = sym__string_content,
  [sym_comment] = sym_comment,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym__command] = sym__command,
  [sym__hash_command] = sym__hash_command,
  [sym_check_command] = sym_check_command,
  [sym_eval_command] = sym_eval_command,
  [sym_reduce_command] = sym_reduce_command,
  [sym_namespace_definition] = sym_namespace_definition,
  [sym_section_definition] = sym_section_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_annotated] = sym_annotated,
  [sym__type_annotation] = sym__type_annotation,
  [sym_function_annotation] = sym_function_annotation,
  [sym_function_definition] = sym_function_definition,
  [sym_theorem_definition] = sym_theorem_definition,
  [sym_example_definition] = sym_example_definition,
  [sym__expression] = sym__expression,
  [sym__parenthesized_expression] = sym__parenthesized_expression,
  [sym_conditional] = sym_conditional,
  [sym_lambda] = sym_lambda,
  [sym_function_application] = sym_function_application,
  [sym_binary_expression] = sym_binary_expression,
  [sym_comparison] = sym_comparison,
  [sym_string] = sym_string,
  [sym_interpolation] = sym_interpolation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_function_application_repeat1] = aux_sym_function_application_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDcheck] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDeval] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDreduce] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_section] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_theorem] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_example] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fun] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__command] = {
    .visible = false,
    .named = true,
  },
  [sym__hash_command] = {
    .visible = false,
    .named = true,
  },
  [sym_check_command] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_command] = {
    .visible = true,
    .named = true,
  },
  [sym_reduce_command] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_section_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_annotated] = {
    .visible = true,
    .named = true,
  },
  [sym__type_annotation] = {
    .visible = false,
    .named = true,
  },
  [sym_function_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_theorem_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_example_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__parenthesized_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_function_application] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_application_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_name = 2,
  field_parameters = 3,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_name] = "name",
  [field_parameters] = "parameters",
};

static const TSFieldMapSlice ts_field_map_slices[4] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arguments, 1},
    {field_name, 0},
  [2] =
    {field_name, 1},
  [3] =
    {field_name, 1},
    {field_parameters, 2},
};

static TSSymbol ts_alias_sequences[4][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '#') ADVANCE(8);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == ':') ADVANCE(27);
      if (lookahead == '<') ADVANCE(37);
      if (lookahead == '=') ADVANCE(36);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == '{') ADVANCE(40);
      if (lookahead == '}') ADVANCE(41);
      if (lookahead == 8594) ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '{') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ':') ADVANCE(27);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ':') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(45);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(15);
      if (lookahead == 'e') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'k') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 19:
      if (lookahead == 'v') ADVANCE(7);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '#') ADVANCE(8);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '<') ADVANCE(37);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == '}') ADVANCE(41);
      if (lookahead == 8594) ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(20)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUNDcheck);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_POUNDeval);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_POUNDreduce);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(45);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(31);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__string_content);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '-') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '{') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(42);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '!' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(9);
      if (lookahead == 'n') ADVANCE(10);
      if (lookahead == 'x') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'h') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(26);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_fun);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(29);
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 38:
      if (lookahead == 'm') ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_example);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_section);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_theorem);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 20},
  [3] = {.lex_state = 20},
  [4] = {.lex_state = 20},
  [5] = {.lex_state = 20},
  [6] = {.lex_state = 20},
  [7] = {.lex_state = 20},
  [8] = {.lex_state = 20},
  [9] = {.lex_state = 20},
  [10] = {.lex_state = 20},
  [11] = {.lex_state = 20},
  [12] = {.lex_state = 20},
  [13] = {.lex_state = 20},
  [14] = {.lex_state = 20},
  [15] = {.lex_state = 20},
  [16] = {.lex_state = 20},
  [17] = {.lex_state = 20},
  [18] = {.lex_state = 20},
  [19] = {.lex_state = 20},
  [20] = {.lex_state = 20},
  [21] = {.lex_state = 20},
  [22] = {.lex_state = 20},
  [23] = {.lex_state = 20},
  [24] = {.lex_state = 20},
  [25] = {.lex_state = 20},
  [26] = {.lex_state = 20},
  [27] = {.lex_state = 20},
  [28] = {.lex_state = 20},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 20},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 20},
  [89] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_POUNDcheck] = ACTIONS(1),
    [anon_sym_POUNDeval] = ACTIONS(1),
    [anon_sym_POUNDreduce] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_section] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_theorem] = ACTIONS(1),
    [anon_sym_example] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_fun] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(73),
    [sym__command] = STATE(32),
    [sym__hash_command] = STATE(32),
    [sym_check_command] = STATE(32),
    [sym_eval_command] = STATE(32),
    [sym_reduce_command] = STATE(32),
    [sym_namespace_definition] = STATE(32),
    [sym_section_definition] = STATE(32),
    [sym_function_definition] = STATE(32),
    [sym_theorem_definition] = STATE(32),
    [sym_example_definition] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUNDcheck] = ACTIONS(7),
    [anon_sym_POUNDeval] = ACTIONS(9),
    [anon_sym_POUNDreduce] = ACTIONS(11),
    [anon_sym_namespace] = ACTIONS(13),
    [anon_sym_section] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_theorem] = ACTIONS(19),
    [anon_sym_example] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_POUNDcheck] = ACTIONS(23),
    [anon_sym_POUNDeval] = ACTIONS(23),
    [anon_sym_POUNDreduce] = ACTIONS(23),
    [anon_sym_namespace] = ACTIONS(27),
    [anon_sym_end] = ACTIONS(27),
    [anon_sym_section] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_] = ACTIONS(23),
    [anon_sym_def] = ACTIONS(27),
    [anon_sym_COLON_EQ] = ACTIONS(23),
    [anon_sym_theorem] = ACTIONS(27),
    [anon_sym_example] = ACTIONS(27),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_then] = ACTIONS(27),
    [anon_sym_else] = ACTIONS(27),
    [anon_sym_fun] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(37),
  },
  [3] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_identifier] = ACTIONS(41),
    [anon_sym_POUNDcheck] = ACTIONS(39),
    [anon_sym_POUNDeval] = ACTIONS(39),
    [anon_sym_POUNDreduce] = ACTIONS(39),
    [anon_sym_namespace] = ACTIONS(41),
    [anon_sym_end] = ACTIONS(41),
    [anon_sym_section] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_] = ACTIONS(39),
    [anon_sym_def] = ACTIONS(41),
    [anon_sym_COLON_EQ] = ACTIONS(39),
    [anon_sym_theorem] = ACTIONS(41),
    [anon_sym_example] = ACTIONS(41),
    [anon_sym_if] = ACTIONS(41),
    [anon_sym_then] = ACTIONS(41),
    [anon_sym_else] = ACTIONS(41),
    [anon_sym_fun] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(39),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(39),
    [anon_sym_RBRACE] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(39),
  },
  [4] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_identifier] = ACTIONS(51),
    [anon_sym_POUNDcheck] = ACTIONS(49),
    [anon_sym_POUNDeval] = ACTIONS(49),
    [anon_sym_POUNDreduce] = ACTIONS(49),
    [anon_sym_namespace] = ACTIONS(51),
    [anon_sym_end] = ACTIONS(51),
    [anon_sym_section] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(49),
    [anon_sym_RPAREN] = ACTIONS(49),
    [anon_sym_] = ACTIONS(49),
    [anon_sym_def] = ACTIONS(51),
    [anon_sym_COLON_EQ] = ACTIONS(49),
    [anon_sym_theorem] = ACTIONS(51),
    [anon_sym_example] = ACTIONS(51),
    [anon_sym_if] = ACTIONS(51),
    [anon_sym_then] = ACTIONS(51),
    [anon_sym_else] = ACTIONS(51),
    [anon_sym_fun] = ACTIONS(51),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(49),
    [anon_sym_LT] = ACTIONS(49),
    [anon_sym_GT] = ACTIONS(49),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(49),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(49),
  },
  [5] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_identifier] = ACTIONS(55),
    [anon_sym_POUNDcheck] = ACTIONS(53),
    [anon_sym_POUNDeval] = ACTIONS(53),
    [anon_sym_POUNDreduce] = ACTIONS(53),
    [anon_sym_namespace] = ACTIONS(55),
    [anon_sym_end] = ACTIONS(55),
    [anon_sym_section] = ACTIONS(55),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_RPAREN] = ACTIONS(53),
    [anon_sym_] = ACTIONS(53),
    [anon_sym_def] = ACTIONS(55),
    [anon_sym_COLON_EQ] = ACTIONS(53),
    [anon_sym_theorem] = ACTIONS(55),
    [anon_sym_example] = ACTIONS(55),
    [anon_sym_if] = ACTIONS(55),
    [anon_sym_then] = ACTIONS(55),
    [anon_sym_else] = ACTIONS(55),
    [anon_sym_fun] = ACTIONS(55),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(53),
    [anon_sym_LT] = ACTIONS(53),
    [anon_sym_GT] = ACTIONS(53),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [anon_sym_RBRACE] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(53),
  },
  [6] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_identifier] = ACTIONS(59),
    [anon_sym_POUNDcheck] = ACTIONS(57),
    [anon_sym_POUNDeval] = ACTIONS(57),
    [anon_sym_POUNDreduce] = ACTIONS(57),
    [anon_sym_namespace] = ACTIONS(59),
    [anon_sym_end] = ACTIONS(59),
    [anon_sym_section] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_] = ACTIONS(57),
    [anon_sym_def] = ACTIONS(59),
    [anon_sym_COLON_EQ] = ACTIONS(57),
    [anon_sym_theorem] = ACTIONS(59),
    [anon_sym_example] = ACTIONS(59),
    [anon_sym_if] = ACTIONS(59),
    [anon_sym_then] = ACTIONS(59),
    [anon_sym_else] = ACTIONS(59),
    [anon_sym_fun] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(57),
    [anon_sym_PLUS] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_EQ] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(57),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(57),
  },
  [7] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_identifier] = ACTIONS(59),
    [anon_sym_POUNDcheck] = ACTIONS(57),
    [anon_sym_POUNDeval] = ACTIONS(57),
    [anon_sym_POUNDreduce] = ACTIONS(57),
    [anon_sym_namespace] = ACTIONS(59),
    [anon_sym_end] = ACTIONS(59),
    [anon_sym_section] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_] = ACTIONS(57),
    [anon_sym_def] = ACTIONS(59),
    [anon_sym_COLON_EQ] = ACTIONS(57),
    [anon_sym_theorem] = ACTIONS(59),
    [anon_sym_example] = ACTIONS(59),
    [anon_sym_if] = ACTIONS(59),
    [anon_sym_then] = ACTIONS(59),
    [anon_sym_else] = ACTIONS(59),
    [anon_sym_fun] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_EQ] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(57),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(57),
  },
  [8] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_identifier] = ACTIONS(59),
    [anon_sym_POUNDcheck] = ACTIONS(57),
    [anon_sym_POUNDeval] = ACTIONS(57),
    [anon_sym_POUNDreduce] = ACTIONS(57),
    [anon_sym_namespace] = ACTIONS(59),
    [anon_sym_end] = ACTIONS(59),
    [anon_sym_section] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_] = ACTIONS(57),
    [anon_sym_def] = ACTIONS(59),
    [anon_sym_COLON_EQ] = ACTIONS(57),
    [anon_sym_theorem] = ACTIONS(59),
    [anon_sym_example] = ACTIONS(59),
    [anon_sym_if] = ACTIONS(59),
    [anon_sym_then] = ACTIONS(59),
    [anon_sym_else] = ACTIONS(59),
    [anon_sym_fun] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(57),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(57),
  },
  [9] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_identifier] = ACTIONS(63),
    [anon_sym_POUNDcheck] = ACTIONS(61),
    [anon_sym_POUNDeval] = ACTIONS(61),
    [anon_sym_POUNDreduce] = ACTIONS(61),
    [anon_sym_namespace] = ACTIONS(66),
    [anon_sym_end] = ACTIONS(66),
    [anon_sym_section] = ACTIONS(66),
    [anon_sym_LPAREN] = ACTIONS(68),
    [anon_sym_RPAREN] = ACTIONS(61),
    [anon_sym_] = ACTIONS(61),
    [anon_sym_def] = ACTIONS(66),
    [anon_sym_COLON_EQ] = ACTIONS(61),
    [anon_sym_theorem] = ACTIONS(66),
    [anon_sym_example] = ACTIONS(66),
    [anon_sym_if] = ACTIONS(71),
    [anon_sym_then] = ACTIONS(66),
    [anon_sym_else] = ACTIONS(66),
    [anon_sym_fun] = ACTIONS(74),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_EQ] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(80),
  },
  [10] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(83),
    [sym_identifier] = ACTIONS(85),
    [anon_sym_POUNDcheck] = ACTIONS(83),
    [anon_sym_POUNDeval] = ACTIONS(83),
    [anon_sym_POUNDreduce] = ACTIONS(83),
    [anon_sym_namespace] = ACTIONS(85),
    [anon_sym_end] = ACTIONS(85),
    [anon_sym_section] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(83),
    [anon_sym_RPAREN] = ACTIONS(83),
    [anon_sym_] = ACTIONS(83),
    [anon_sym_def] = ACTIONS(85),
    [anon_sym_COLON_EQ] = ACTIONS(83),
    [anon_sym_theorem] = ACTIONS(85),
    [anon_sym_example] = ACTIONS(85),
    [anon_sym_if] = ACTIONS(85),
    [anon_sym_then] = ACTIONS(85),
    [anon_sym_else] = ACTIONS(85),
    [anon_sym_fun] = ACTIONS(85),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_LT] = ACTIONS(83),
    [anon_sym_GT] = ACTIONS(83),
    [anon_sym_DQUOTE] = ACTIONS(83),
    [anon_sym_RBRACE] = ACTIONS(83),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(83),
  },
  [11] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(87),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_POUNDcheck] = ACTIONS(87),
    [anon_sym_POUNDeval] = ACTIONS(87),
    [anon_sym_POUNDreduce] = ACTIONS(87),
    [anon_sym_namespace] = ACTIONS(89),
    [anon_sym_end] = ACTIONS(89),
    [anon_sym_section] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_def] = ACTIONS(89),
    [anon_sym_theorem] = ACTIONS(89),
    [anon_sym_example] = ACTIONS(89),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_fun] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_LT] = ACTIONS(93),
    [anon_sym_GT] = ACTIONS(93),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(37),
  },
  [12] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(95),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_POUNDcheck] = ACTIONS(95),
    [anon_sym_POUNDeval] = ACTIONS(95),
    [anon_sym_POUNDreduce] = ACTIONS(95),
    [anon_sym_namespace] = ACTIONS(97),
    [anon_sym_end] = ACTIONS(97),
    [anon_sym_section] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_def] = ACTIONS(97),
    [anon_sym_theorem] = ACTIONS(97),
    [anon_sym_example] = ACTIONS(97),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_fun] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_LT] = ACTIONS(93),
    [anon_sym_GT] = ACTIONS(93),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(37),
  },
  [13] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(99),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_POUNDcheck] = ACTIONS(99),
    [anon_sym_POUNDeval] = ACTIONS(99),
    [anon_sym_POUNDreduce] = ACTIONS(99),
    [anon_sym_namespace] = ACTIONS(101),
    [anon_sym_end] = ACTIONS(101),
    [anon_sym_section] = ACTIONS(101),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_def] = ACTIONS(101),
    [anon_sym_theorem] = ACTIONS(101),
    [anon_sym_example] = ACTIONS(101),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_fun] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_LT] = ACTIONS(93),
    [anon_sym_GT] = ACTIONS(93),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(37),
  },
  [14] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(103),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_POUNDcheck] = ACTIONS(103),
    [anon_sym_POUNDeval] = ACTIONS(103),
    [anon_sym_POUNDreduce] = ACTIONS(103),
    [anon_sym_namespace] = ACTIONS(105),
    [anon_sym_end] = ACTIONS(105),
    [anon_sym_section] = ACTIONS(105),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_def] = ACTIONS(105),
    [anon_sym_theorem] = ACTIONS(105),
    [anon_sym_example] = ACTIONS(105),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_fun] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_LT] = ACTIONS(93),
    [anon_sym_GT] = ACTIONS(93),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(37),
  },
  [15] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(107),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_POUNDcheck] = ACTIONS(107),
    [anon_sym_POUNDeval] = ACTIONS(107),
    [anon_sym_POUNDreduce] = ACTIONS(107),
    [anon_sym_namespace] = ACTIONS(109),
    [anon_sym_end] = ACTIONS(109),
    [anon_sym_section] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_def] = ACTIONS(109),
    [anon_sym_theorem] = ACTIONS(109),
    [anon_sym_example] = ACTIONS(109),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_fun] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_LT] = ACTIONS(93),
    [anon_sym_GT] = ACTIONS(93),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(37),
  },
  [16] = {
    [sym__expression] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym_conditional] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_function_application] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_comparison] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_function_application_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(111),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_POUNDcheck] = ACTIONS(111),
    [anon_sym_POUNDeval] = ACTIONS(111),
    [anon_sym_POUNDreduce] = ACTIONS(111),
    [anon_sym_namespace] = ACTIONS(113),
    [anon_sym_end] = ACTIONS(113),
    [anon_sym_section] = ACTIONS(113),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_def] = ACTIONS(113),
    [anon_sym_theorem] = ACTIONS(113),
    [anon_sym_example] = ACTIONS(113),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_fun] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_LT] = ACTIONS(93),
    [anon_sym_GT] = ACTIONS(93),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(37),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 12,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fun,
      anon_sym_DASH,
      sym_identifier,
    ACTIONS(115), 16,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_number,
  [36] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 12,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fun,
      anon_sym_DASH,
      sym_identifier,
    ACTIONS(119), 16,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_number,
  [72] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 12,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fun,
      anon_sym_DASH,
      sym_identifier,
    ACTIONS(123), 16,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_COLON_EQ,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_number,
  [108] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      sym_number,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_PLUS,
    ACTIONS(47), 1,
      anon_sym_DASH,
    ACTIONS(91), 1,
      anon_sym_EQ,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    ACTIONS(129), 1,
      anon_sym_,
    STATE(2), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(4), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [165] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      sym_number,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_PLUS,
    ACTIONS(47), 1,
      anon_sym_DASH,
    ACTIONS(91), 1,
      anon_sym_EQ,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
    STATE(2), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(4), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [219] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      sym_number,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_PLUS,
    ACTIONS(47), 1,
      anon_sym_DASH,
    ACTIONS(91), 1,
      anon_sym_EQ,
    ACTIONS(133), 1,
      anon_sym_COLON_EQ,
    STATE(2), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(4), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [273] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      sym_number,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_PLUS,
    ACTIONS(47), 1,
      anon_sym_DASH,
    ACTIONS(91), 1,
      anon_sym_EQ,
    ACTIONS(135), 1,
      anon_sym_else,
    STATE(2), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(4), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [327] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      sym_number,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_PLUS,
    ACTIONS(47), 1,
      anon_sym_DASH,
    ACTIONS(91), 1,
      anon_sym_EQ,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    STATE(2), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(4), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [381] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      sym_number,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_PLUS,
    ACTIONS(47), 1,
      anon_sym_DASH,
    ACTIONS(91), 1,
      anon_sym_EQ,
    ACTIONS(139), 1,
      anon_sym_then,
    STATE(2), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(4), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [435] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      sym_number,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_PLUS,
    ACTIONS(47), 1,
      anon_sym_DASH,
    ACTIONS(91), 1,
      anon_sym_EQ,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(4), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [489] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      sym_number,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_PLUS,
    ACTIONS(47), 1,
      anon_sym_DASH,
    ACTIONS(91), 1,
      anon_sym_EQ,
    ACTIONS(143), 1,
      anon_sym_COLON_EQ,
    STATE(2), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(4), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [543] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      sym_number,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_PLUS,
    ACTIONS(47), 1,
      anon_sym_DASH,
    ACTIONS(91), 1,
      anon_sym_EQ,
    ACTIONS(145), 1,
      anon_sym_COLON_EQ,
    STATE(2), 1,
      aux_sym_function_application_repeat1,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(4), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [597] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_POUNDcheck,
    ACTIONS(152), 1,
      anon_sym_POUNDeval,
    ACTIONS(155), 1,
      anon_sym_POUNDreduce,
    ACTIONS(158), 1,
      anon_sym_namespace,
    ACTIONS(161), 1,
      anon_sym_section,
    ACTIONS(164), 1,
      anon_sym_def,
    ACTIONS(167), 1,
      anon_sym_theorem,
    ACTIONS(170), 1,
      anon_sym_example,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    STATE(29), 11,
      sym__command,
      sym__hash_command,
      sym_check_command,
      sym_eval_command,
      sym_reduce_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [642] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_POUNDcheck,
    ACTIONS(9), 1,
      anon_sym_POUNDeval,
    ACTIONS(11), 1,
      anon_sym_POUNDreduce,
    ACTIONS(13), 1,
      anon_sym_namespace,
    ACTIONS(15), 1,
      anon_sym_section,
    ACTIONS(17), 1,
      anon_sym_def,
    ACTIONS(19), 1,
      anon_sym_theorem,
    ACTIONS(21), 1,
      anon_sym_example,
    ACTIONS(173), 1,
      anon_sym_end,
    STATE(34), 11,
      sym__command,
      sym__hash_command,
      sym_check_command,
      sym_eval_command,
      sym_reduce_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [686] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_POUNDcheck,
    ACTIONS(9), 1,
      anon_sym_POUNDeval,
    ACTIONS(11), 1,
      anon_sym_POUNDreduce,
    ACTIONS(13), 1,
      anon_sym_namespace,
    ACTIONS(15), 1,
      anon_sym_section,
    ACTIONS(17), 1,
      anon_sym_def,
    ACTIONS(19), 1,
      anon_sym_theorem,
    ACTIONS(21), 1,
      anon_sym_example,
    ACTIONS(175), 1,
      anon_sym_end,
    STATE(33), 11,
      sym__command,
      sym__hash_command,
      sym_check_command,
      sym_eval_command,
      sym_reduce_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [730] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_POUNDcheck,
    ACTIONS(9), 1,
      anon_sym_POUNDeval,
    ACTIONS(11), 1,
      anon_sym_POUNDreduce,
    ACTIONS(13), 1,
      anon_sym_namespace,
    ACTIONS(15), 1,
      anon_sym_section,
    ACTIONS(17), 1,
      anon_sym_def,
    ACTIONS(19), 1,
      anon_sym_theorem,
    ACTIONS(21), 1,
      anon_sym_example,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
    STATE(29), 11,
      sym__command,
      sym__hash_command,
      sym_check_command,
      sym_eval_command,
      sym_reduce_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [774] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_POUNDcheck,
    ACTIONS(9), 1,
      anon_sym_POUNDeval,
    ACTIONS(11), 1,
      anon_sym_POUNDreduce,
    ACTIONS(13), 1,
      anon_sym_namespace,
    ACTIONS(15), 1,
      anon_sym_section,
    ACTIONS(17), 1,
      anon_sym_def,
    ACTIONS(19), 1,
      anon_sym_theorem,
    ACTIONS(21), 1,
      anon_sym_example,
    ACTIONS(179), 1,
      anon_sym_end,
    STATE(29), 11,
      sym__command,
      sym__hash_command,
      sym_check_command,
      sym_eval_command,
      sym_reduce_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [818] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_POUNDcheck,
    ACTIONS(9), 1,
      anon_sym_POUNDeval,
    ACTIONS(11), 1,
      anon_sym_POUNDreduce,
    ACTIONS(13), 1,
      anon_sym_namespace,
    ACTIONS(15), 1,
      anon_sym_section,
    ACTIONS(17), 1,
      anon_sym_def,
    ACTIONS(19), 1,
      anon_sym_theorem,
    ACTIONS(21), 1,
      anon_sym_example,
    ACTIONS(181), 1,
      anon_sym_end,
    STATE(29), 11,
      sym__command,
      sym__hash_command,
      sym_check_command,
      sym_eval_command,
      sym_reduce_command,
      sym_namespace_definition,
      sym_section_definition,
      sym_function_definition,
      sym_theorem_definition,
      sym_example_definition,
      aux_sym_source_file_repeat1,
  [862] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(185), 1,
      sym_number,
    STATE(81), 2,
      sym__type_annotation,
      sym_function_annotation,
    STATE(20), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [898] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 1,
      sym_number,
    STATE(22), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [930] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(191), 1,
      sym_identifier,
    ACTIONS(193), 1,
      sym_number,
    STATE(3), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [962] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym_number,
    STATE(6), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [994] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(199), 1,
      sym_identifier,
    ACTIONS(201), 1,
      sym_number,
    STATE(7), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1026] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(203), 1,
      sym_identifier,
    ACTIONS(205), 1,
      sym_number,
    STATE(8), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1058] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(207), 1,
      sym_identifier,
    ACTIONS(209), 1,
      sym_number,
    STATE(10), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1090] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(211), 1,
      sym_identifier,
    ACTIONS(213), 1,
      sym_number,
    STATE(11), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1122] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(217), 1,
      sym_number,
    STATE(24), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1154] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(221), 1,
      sym_number,
    STATE(15), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1186] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(225), 1,
      sym_number,
    STATE(21), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1218] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(227), 1,
      sym_identifier,
    ACTIONS(229), 1,
      sym_number,
    STATE(12), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1250] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(231), 1,
      sym_identifier,
    ACTIONS(233), 1,
      sym_number,
    STATE(16), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1282] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(235), 1,
      sym_identifier,
    ACTIONS(237), 1,
      sym_number,
    STATE(26), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1314] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(239), 1,
      sym_identifier,
    ACTIONS(241), 1,
      sym_number,
    STATE(23), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1346] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(243), 1,
      sym_identifier,
    ACTIONS(245), 1,
      sym_number,
    STATE(14), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1378] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(247), 1,
      sym_identifier,
    ACTIONS(249), 1,
      sym_number,
    STATE(5), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1410] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(253), 1,
      sym_number,
    STATE(28), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1442] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(255), 1,
      sym_identifier,
    ACTIONS(257), 1,
      sym_number,
    STATE(25), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1474] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(259), 1,
      sym_identifier,
    ACTIONS(261), 1,
      sym_number,
    STATE(13), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1506] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_fun,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(263), 1,
      sym_identifier,
    ACTIONS(265), 1,
      sym_number,
    STATE(27), 8,
      sym__expression,
      sym__parenthesized_expression,
      sym_conditional,
      sym_lambda,
      sym_function_application,
      sym_binary_expression,
      sym_comparison,
      sym_string,
  [1538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 10,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1554] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 10,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1570] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 10,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 10,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1602] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 10,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 10,
      ts_builtin_sym_end,
      anon_sym_POUNDcheck,
      anon_sym_POUNDeval,
      anon_sym_POUNDreduce,
      anon_sym_namespace,
      anon_sym_end,
      anon_sym_section,
      anon_sym_def,
      anon_sym_theorem,
      anon_sym_example,
  [1634] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym_identifier,
    ACTIONS(281), 1,
      anon_sym_LPAREN,
    ACTIONS(283), 1,
      anon_sym_COLON,
    ACTIONS(285), 2,
      anon_sym_COLON_EQ,
      anon_sym_EQ_GT,
    STATE(63), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1655] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym_identifier,
    ACTIONS(290), 1,
      anon_sym_LPAREN,
    ACTIONS(293), 1,
      anon_sym_COLON,
    ACTIONS(295), 2,
      anon_sym_COLON_EQ,
      anon_sym_EQ_GT,
    STATE(63), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1676] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_LPAREN,
    ACTIONS(297), 1,
      sym_identifier,
    ACTIONS(299), 1,
      anon_sym_COLON,
    STATE(87), 1,
      sym_parameter_list,
    STATE(62), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1696] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_LPAREN,
    ACTIONS(297), 1,
      sym_identifier,
    ACTIONS(301), 1,
      anon_sym_COLON_EQ,
    STATE(88), 1,
      sym_parameter_list,
    STATE(62), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1716] = 5,
    ACTIONS(303), 1,
      anon_sym_DQUOTE,
    ACTIONS(305), 1,
      anon_sym_LBRACE,
    ACTIONS(307), 1,
      sym__string_content,
    ACTIONS(309), 1,
      sym_comment,
    STATE(67), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1733] = 5,
    ACTIONS(305), 1,
      anon_sym_LBRACE,
    ACTIONS(309), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_DQUOTE,
    ACTIONS(313), 1,
      sym__string_content,
    STATE(69), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1750] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_LPAREN,
    ACTIONS(297), 1,
      sym_identifier,
    STATE(85), 1,
      sym_parameter_list,
    STATE(62), 2,
      sym_annotated,
      aux_sym_parameter_list_repeat1,
  [1767] = 5,
    ACTIONS(309), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_DQUOTE,
    ACTIONS(317), 1,
      anon_sym_LBRACE,
    ACTIONS(320), 1,
      sym__string_content,
    STATE(69), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1784] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_COLON,
    ACTIONS(323), 4,
      anon_sym_LPAREN,
      anon_sym_COLON_EQ,
      anon_sym_EQ_GT,
      sym_identifier,
  [1797] = 2,
    ACTIONS(309), 1,
      sym_comment,
    ACTIONS(327), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym__string_content,
  [1806] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      sym_identifier,
  [1813] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      ts_builtin_sym_end,
  [1820] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_COLON,
  [1827] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      sym_identifier,
  [1834] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      sym_identifier,
  [1841] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      sym_identifier,
  [1848] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_identifier,
  [1855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      sym_identifier,
  [1862] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      sym_identifier,
  [1869] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_RPAREN,
  [1876] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      sym_identifier,
  [1883] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      sym_identifier,
  [1890] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      sym_identifier,
  [1897] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_EQ_GT,
  [1904] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_COLON,
  [1911] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_COLON,
  [1918] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_COLON_EQ,
  [1925] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      sym_identifier,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(17)] = 0,
  [SMALL_STATE(18)] = 36,
  [SMALL_STATE(19)] = 72,
  [SMALL_STATE(20)] = 108,
  [SMALL_STATE(21)] = 165,
  [SMALL_STATE(22)] = 219,
  [SMALL_STATE(23)] = 273,
  [SMALL_STATE(24)] = 327,
  [SMALL_STATE(25)] = 381,
  [SMALL_STATE(26)] = 435,
  [SMALL_STATE(27)] = 489,
  [SMALL_STATE(28)] = 543,
  [SMALL_STATE(29)] = 597,
  [SMALL_STATE(30)] = 642,
  [SMALL_STATE(31)] = 686,
  [SMALL_STATE(32)] = 730,
  [SMALL_STATE(33)] = 774,
  [SMALL_STATE(34)] = 818,
  [SMALL_STATE(35)] = 862,
  [SMALL_STATE(36)] = 898,
  [SMALL_STATE(37)] = 930,
  [SMALL_STATE(38)] = 962,
  [SMALL_STATE(39)] = 994,
  [SMALL_STATE(40)] = 1026,
  [SMALL_STATE(41)] = 1058,
  [SMALL_STATE(42)] = 1090,
  [SMALL_STATE(43)] = 1122,
  [SMALL_STATE(44)] = 1154,
  [SMALL_STATE(45)] = 1186,
  [SMALL_STATE(46)] = 1218,
  [SMALL_STATE(47)] = 1250,
  [SMALL_STATE(48)] = 1282,
  [SMALL_STATE(49)] = 1314,
  [SMALL_STATE(50)] = 1346,
  [SMALL_STATE(51)] = 1378,
  [SMALL_STATE(52)] = 1410,
  [SMALL_STATE(53)] = 1442,
  [SMALL_STATE(54)] = 1474,
  [SMALL_STATE(55)] = 1506,
  [SMALL_STATE(56)] = 1538,
  [SMALL_STATE(57)] = 1554,
  [SMALL_STATE(58)] = 1570,
  [SMALL_STATE(59)] = 1586,
  [SMALL_STATE(60)] = 1602,
  [SMALL_STATE(61)] = 1618,
  [SMALL_STATE(62)] = 1634,
  [SMALL_STATE(63)] = 1655,
  [SMALL_STATE(64)] = 1676,
  [SMALL_STATE(65)] = 1696,
  [SMALL_STATE(66)] = 1716,
  [SMALL_STATE(67)] = 1733,
  [SMALL_STATE(68)] = 1750,
  [SMALL_STATE(69)] = 1767,
  [SMALL_STATE(70)] = 1784,
  [SMALL_STATE(71)] = 1797,
  [SMALL_STATE(72)] = 1806,
  [SMALL_STATE(73)] = 1813,
  [SMALL_STATE(74)] = 1820,
  [SMALL_STATE(75)] = 1827,
  [SMALL_STATE(76)] = 1834,
  [SMALL_STATE(77)] = 1841,
  [SMALL_STATE(78)] = 1848,
  [SMALL_STATE(79)] = 1855,
  [SMALL_STATE(80)] = 1862,
  [SMALL_STATE(81)] = 1869,
  [SMALL_STATE(82)] = 1876,
  [SMALL_STATE(83)] = 1883,
  [SMALL_STATE(84)] = 1890,
  [SMALL_STATE(85)] = 1897,
  [SMALL_STATE(86)] = 1904,
  [SMALL_STATE(87)] = 1911,
  [SMALL_STATE(88)] = 1918,
  [SMALL_STATE(89)] = 1925,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_application, 2, .production_id = 1),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_application, 2, .production_id = 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 6),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 6),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_application_repeat1, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_application_repeat1, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 4),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda, 4),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_application_repeat1, 2),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(4),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_application_repeat1, 2),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(43),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(53),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(68),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(66),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_application_repeat1, 2), SHIFT_REPEAT(4),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 3),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eval_command, 2),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eval_command, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_example_definition, 5),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_example_definition, 5),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, .production_id = 3),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5, .production_id = 3),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reduce_command, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reduce_command, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, .production_id = 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, .production_id = 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_check_command, 2),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_check_command, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesized_expression, 3),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__parenthesized_expression, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_annotation, 1),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_annotation, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(47),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(42),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(50),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(82),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(79),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(78),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(76),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(74),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_definition, 4, .production_id = 2),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theorem_definition, 7, .production_id = 3),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_definition, 5, .production_id = 2),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 4, .production_id = 2),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 5, .production_id = 2),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theorem_definition, 6, .production_id = 2),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 1),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1),
  [287] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(63),
  [290] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(83),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [303] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [309] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [313] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [315] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [317] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(48),
  [320] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(69),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotated, 5),
  [325] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotated, 5),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [331] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_lean(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
