name: CI

on:
  push:
    branches-ignore:
      - "wip*"
  pull_request:
  schedule:
    # Daily at 1:21
    - cron: '21 1 * * *'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  ci:
    name: Test the grammar
    runs-on: ubuntu-latest

    steps:
      - uses: tree-sitter/setup-action@49f8c1f20b60102eae8c033bb7c7f6cd056f6086
        with:
          install-lib: false
          # Until tree-sitter generate's performance improvements hit a release
          tree-sitter-ref: nightly
      - run: tree-sitter generate
      - run: tree-sitter test
